// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: agent_comm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssetInfo 资产信息
type AssetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsType        string                 `protobuf:"bytes,3,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetInfo) Reset() {
	*x = AssetInfo{}
	mi := &file_agent_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetInfo) ProtoMessage() {}

func (x *AssetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetInfo.ProtoReflect.Descriptor instead.
func (*AssetInfo) Descriptor() ([]byte, []int) {
	return file_agent_comm_proto_rawDescGZIP(), []int{0}
}

func (x *AssetInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AssetInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AssetInfo) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *AssetInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *AssetInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AssetInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// RegisterRequest 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	AssetInfo     *AssetInfo             `protobuf:"bytes,2,opt,name=asset_info,json=assetInfo,proto3" json:"asset_info,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_comm_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterRequest) GetAssetInfo() *AssetInfo {
	if x != nil {
		return x.AssetInfo
	}
	return nil
}

func (x *RegisterRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// RegisterResponse 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_comm_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HeartbeatRequest 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_comm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_comm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_comm_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HeartbeatResponse 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_comm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_comm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_comm_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CommandExecute 命令执行
type CommandExecute struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RuleId         string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	HostId         string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ScriptContent  string                 `protobuf:"bytes,4,opt,name=script_content,json=scriptContent,proto3" json:"script_content,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandExecute) Reset() {
	*x = CommandExecute{}
	mi := &file_agent_comm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExecute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecute) ProtoMessage() {}

func (x *CommandExecute) ProtoReflect() protoreflect.Message {
	mi := &file_agent_comm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecute.ProtoReflect.Descriptor instead.
func (*CommandExecute) Descriptor() ([]byte, []int) {
	return file_agent_comm_proto_rawDescGZIP(), []int{5}
}

func (x *CommandExecute) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CommandExecute) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *CommandExecute) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CommandExecute) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

func (x *CommandExecute) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// CommandResult 命令结果
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	IsFinal       bool                   `protobuf:"varint,6,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_agent_comm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_comm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_agent_comm_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CommandResult) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// CommandRequest 命令请求
type CommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*CommandRequest_Execute
	//	*CommandRequest_Result
	Request       isCommandRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_agent_comm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_comm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_agent_comm_proto_rawDescGZIP(), []int{7}
}

func (x *CommandRequest) GetRequest() isCommandRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CommandRequest) GetExecute() *CommandExecute {
	if x != nil {
		if x, ok := x.Request.(*CommandRequest_Execute); ok {
			return x.Execute
		}
	}
	return nil
}

func (x *CommandRequest) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Request.(*CommandRequest_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isCommandRequest_Request interface {
	isCommandRequest_Request()
}

type CommandRequest_Execute struct {
	Execute *CommandExecute `protobuf:"bytes,1,opt,name=execute,proto3,oneof"`
}

type CommandRequest_Result struct {
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*CommandRequest_Execute) isCommandRequest_Request() {}

func (*CommandRequest_Result) isCommandRequest_Request() {}

var File_agent_comm_proto protoreflect.FileDescriptor

const file_agent_comm_proto_rawDesc = "" +
	"\n" +
	"\x10agent_comm.proto\x12\ragent_comm.v1\"\xb7\x01\n" +
	"\tAssetInfo\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_type\x18\x03 \x01(\tR\x06osType\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\"\x82\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x127\n" +
	"\n" +
	"asset_info\x18\x02 \x01(\v2\x18.agent_comm.v1.AssetInfoR\tassetInfo\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\"_\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"I\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xab\x01\n" +
	"\x0eCommandExecute\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\x12%\n" +
	"\x0escript_content\x18\x04 \x01(\tR\rscriptContent\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"\xa9\x01\n" +
	"\rCommandResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x19\n" +
	"\bis_final\x18\x06 \x01(\bR\aisFinal\"\x8e\x01\n" +
	"\x0eCommandRequest\x129\n" +
	"\aexecute\x18\x01 \x01(\v2\x1d.agent_comm.v1.CommandExecuteH\x00R\aexecute\x126\n" +
	"\x06result\x18\x02 \x01(\v2\x1c.agent_comm.v1.CommandResultH\x00R\x06resultB\t\n" +
	"\arequest2\xff\x01\n" +
	"\fAgentService\x12K\n" +
	"\bRegister\x12\x1e.agent_comm.v1.RegisterRequest\x1a\x1f.agent_comm.v1.RegisterResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.agent_comm.v1.HeartbeatRequest\x1a .agent_comm.v1.HeartbeatResponse\x12R\n" +
	"\x0eExecuteCommand\x12\x1d.agent_comm.v1.CommandRequest\x1a\x1d.agent_comm.v1.CommandRequest(\x010\x01B\x1fZ\x1dbaseline-system/pkg/api/v1;pbb\x06proto3"

var (
	file_agent_comm_proto_rawDescOnce sync.Once
	file_agent_comm_proto_rawDescData []byte
)

func file_agent_comm_proto_rawDescGZIP() []byte {
	file_agent_comm_proto_rawDescOnce.Do(func() {
		file_agent_comm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_comm_proto_rawDesc), len(file_agent_comm_proto_rawDesc)))
	})
	return file_agent_comm_proto_rawDescData
}

var file_agent_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_agent_comm_proto_goTypes = []any{
	(*AssetInfo)(nil),         // 0: agent_comm.v1.AssetInfo
	(*RegisterRequest)(nil),   // 1: agent_comm.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 2: agent_comm.v1.RegisterResponse
	(*HeartbeatRequest)(nil),  // 3: agent_comm.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 4: agent_comm.v1.HeartbeatResponse
	(*CommandExecute)(nil),    // 5: agent_comm.v1.CommandExecute
	(*CommandResult)(nil),     // 6: agent_comm.v1.CommandResult
	(*CommandRequest)(nil),    // 7: agent_comm.v1.CommandRequest
}
var file_agent_comm_proto_depIdxs = []int32{
	0, // 0: agent_comm.v1.RegisterRequest.asset_info:type_name -> agent_comm.v1.AssetInfo
	5, // 1: agent_comm.v1.CommandRequest.execute:type_name -> agent_comm.v1.CommandExecute
	6, // 2: agent_comm.v1.CommandRequest.result:type_name -> agent_comm.v1.CommandResult
	1, // 3: agent_comm.v1.AgentService.Register:input_type -> agent_comm.v1.RegisterRequest
	3, // 4: agent_comm.v1.AgentService.Heartbeat:input_type -> agent_comm.v1.HeartbeatRequest
	7, // 5: agent_comm.v1.AgentService.ExecuteCommand:input_type -> agent_comm.v1.CommandRequest
	2, // 6: agent_comm.v1.AgentService.Register:output_type -> agent_comm.v1.RegisterResponse
	4, // 7: agent_comm.v1.AgentService.Heartbeat:output_type -> agent_comm.v1.HeartbeatResponse
	7, // 8: agent_comm.v1.AgentService.ExecuteCommand:output_type -> agent_comm.v1.CommandRequest
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agent_comm_proto_init() }
func file_agent_comm_proto_init() {
	if File_agent_comm_proto != nil {
		return
	}
	file_agent_comm_proto_msgTypes[7].OneofWrappers = []any{
		(*CommandRequest_Execute)(nil),
		(*CommandRequest_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_comm_proto_rawDesc), len(file_agent_comm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_comm_proto_goTypes,
		DependencyIndexes: file_agent_comm_proto_depIdxs,
		MessageInfos:      file_agent_comm_proto_msgTypes,
	}.Build()
	File_agent_comm_proto = out.File
	file_agent_comm_proto_goTypes = nil
	file_agent_comm_proto_depIdxs = nil
}
