aegis:
  block_action: kill_process
  mitre_id: T1048
description: Detects T1048 - alternative protocol exfiltration
detection:
  condition: selection
  selection:
    CommandLine|re:
    - scp
    - rsync
    - ftp
falsepositives:
- unknown
id: t1048_alternative_protocol_exfiltration
level: critical
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1048
title: Alternative Protocol Exfiltration
