aegis:
  block_action: kill_process
  mitre_id: T1059.003
description: Detects T1059.003 - cmd detection
detection:
  condition: selection
  selection:
    CommandLine|re:
    - cmd.*/c
    - cmd.*/k
    - cmd.*echo
falsepositives:
- unknown
id: t1059_003_cmd_detection
level: high
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1059.003
title: Cmd Detection
