aegis:
  block_action: kill_process
  mitre_id: T1053.003
description: Detects T1053.003 - cron persistence
detection:
  condition: selection
  selection:
    CommandLine|re:
    - crontab.*-e
    - crontab.*-l
    - /etc/cron
    - /var/spool/cron
falsepositives:
- unknown
id: t1053_003_cron_persistence
level: high
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1053.003
title: Cron Persistence
