aegis:
  block_action: kill_process
  mitre_id: T1573
description: Detects T1573 - encrypted channel
detection:
  condition: selection
  selection:
    CommandLine|re:
    - ssh.*-R
    - ssh.*-L
    - ssh.*-D
    - chisel
    - frp
falsepositives:
- unknown
id: t1573_encrypted_channel
level: critical
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1573
title: Encrypted Channel
