aegis:
  block_action: kill_process
  mitre_id: T1592
description: Detects T1592 - host info gathering
detection:
  condition: selection
  selection:
    CommandLine|re:
    - uname.*-a
    - cat.*/proc/version
    - cat.*/etc/issue
falsepositives:
- unknown
id: t1592_host_info_gathering
level: medium
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1592
title: Host Info Gathering
