aegis:
  block_action: kill_process
  mitre_id: T1003.008
description: Detects T1003.008 - password file access
detection:
  condition: selection
  selection:
    CommandLine|re:
    - cat.*/etc/passwd
    - cat.*/etc/shadow
    - cat.*/etc/gshadow
    - getent.*shadow
falsepositives:
- unknown
id: t1003_008_password_file_access
level: critical
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1003.008
title: Password File Access
