aegis:
  block_action: kill_process
  mitre_id: T1486
description: Detects T1486 - ransomware detection
detection:
  condition: selection
  selection:
    CommandLine|re:
    - encrypt
    - ransom
    - \$.*bitcoin
    - \.locked$
falsepositives:
- unknown
id: t1486_ransomware_detection
level: critical
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1486
title: Ransomware Detection
