aegis:
  block_action: kill_process
  mitre_id: T1059.004
description: Detects T1059.004 - reverse shell detection
detection:
  condition: selection
  selection:
    CommandLine|re:
    - /bin/(ba)?sh.*-i
    - nc.*-e.*(/bin/)?(ba)?sh
    - python.*socket.*connect
    - perl.*socket.*connect
    - ruby.*socket.*connect
    - php.*fsockopen
    - mkfifo.*nc
    - socat.*exec
falsepositives:
- unknown
id: t1059_004_reverse_shell_detection
level: critical
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1059.004
title: Reverse Shell Detection
