aegis:
  block_action: kill_process
  mitre_id: T1113
description: Detects T1113 - screen capture
detection:
  condition: selection
  selection:
    CommandLine|re:
    - scrot
    - import
    - xwd
    - xclip.*-selection.*clipboard
falsepositives:
- unknown
id: t1113_screen_capture
level: medium
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1113
title: Screen Capture
