aegis:
  block_action: kill_process
  mitre_id: T1489
description: Detects T1489 - service stop
detection:
  condition: selection
  selection:
    CommandLine|re:
    - systemctl.*stop
    - service.*stop
    - kill.*-9
falsepositives:
- unknown
id: t1489_service_stop
level: high
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1489
title: Service Stop
