aegis:
  block_action: kill_process
  mitre_id: T1021.004
description: Detects T1021.004 - ssh lateral movement
detection:
  condition: selection
  selection:
    CommandLine|re:
    - ssh.*-i
    - ssh.*-o.*StrictHostKeyChecking=no
    - scp.*-i
falsepositives:
- unknown
id: t1021_004_ssh_lateral_movement
level: high
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1021.004
title: Ssh Lateral Movement
