aegis:
  block_action: kill_process
  mitre_id: T1548.003
description: Detects T1548.003 - sudo abuse
detection:
  condition: selection
  selection:
    CommandLine|re:
    - sudo.*-i
    - sudo.*su
    - sudo.*bash
    - sudo.*sh
falsepositives:
- unknown
id: t1548_003_sudo_abuse
level: high
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1548.003
title: Sudo Abuse
