aegis:
  block_action: kill_process
  mitre_id: T1082
description: Detects T1082 - system info discovery
detection:
  condition: selection
  selection:
    CommandLine|re:
    - uname.*-a
    - cat.*/etc/os-release
    - hostname
    - ifconfig
    - ip.*addr
falsepositives:
- unknown
id: t1082_system_info_discovery
level: medium
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1082
title: System Info Discovery
