aegis:
  block_action: kill_process
  mitre_id: T1543.002
description: Detects T1543.002 - systemd persistence
detection:
  condition: selection
  selection:
    CommandLine|re:
    - systemctl.*enable
    - systemctl.*start
    - /etc/systemd/system
    - /lib/systemd/system
falsepositives:
- unknown
id: t1543_002_systemd_persistence
level: high
logsource:
  category: process_creation
  product: linux
status: active
tags:
- attack.t1543.002
title: Systemd Persistence
