package agentguard

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"aegis-agent/internal/logger"
	pb "aegis-agent/pkg/api/v1"

	"github.com/google/uuid"
	"go.uber.org/zap"
)

type RuntimeReporter interface {
	ReportEvents(events []*pb.RuntimeEvent) error
}

type ManagerConfig struct {
	Enabled                bool
	BehaviorMonitorEnabled bool
	ToolAdapterEnabled     bool
	ToolSourceManifest     string
	ToolHookSocket         string
	ToolAdapter            *TrustedToolAdapter
	EnforcementEnabled     bool
	FreezeEnabled          bool
	HostID                 string
	StateDir               string
	SpoolCapacity          int
	ReconcileInterval      time.Duration
	FlushInterval          time.Duration
	Capabilities           *GuardCapabilities
	ActionFS               ActionFileSystem
	ProcessSignaler        ProcessSignaler
	ActionScheduler        ActionScheduler
	CgroupRoot             string
	SelfPID                uint32
	ParentPID              uint32
	FreezeTimeout          time.Duration
}

type isolationStateScanner interface {
	ReadIsolation(pid uint32) (IsolationState, error)
}

type Manager struct {
	cfg            ManagerConfig
	scanner        ProcessScanner
	reporter       RuntimeReporter
	tracker        *IdentityTracker
	reconciler     *Reconciler
	normalizer     *BehaviorNormalizer
	aggregator     *Aggregator
	spool          *PrioritySpool
	bundles        *BundleStore
	monitorAllowed bool
	monitorEnabled atomic.Bool
	toolEnabled    atomic.Bool
	reconcileReset chan time.Duration
	isolationScan  isolationStateScanner
	capabilities   GuardCapabilities
	actions        *ActionExecutor
	toolAdapter    *TrustedToolAdapter
	toolIngress    *ToolHookReceiver
	toolIngressMu  sync.Mutex
	kernelPolicyMu sync.RWMutex
	kernelPolicy   CompiledKernelPolicy
	kernelApply    func(CompiledKernelPolicy, []KernelSubject) error

	statusMu        sync.Mutex
	lifecycleMu     sync.Mutex
	isolationMu     sync.Mutex
	pendingStatus   []*pb.RuntimeEvent
	started         map[string]bool
	startedUnits    map[string]bool
	startedSessions map[string]bool
	lastDrift       map[string]string
	cancel          context.CancelFunc
	wg              sync.WaitGroup
}

func NewManager(cfg ManagerConfig, scanner ProcessScanner, reporter RuntimeReporter) *Manager {
	if scanner == nil {
		scanner = NewProcFSScanner("/proc")
	}
	if cfg.StateDir == "" {
		cfg.StateDir = "/var/lib/aegis/agent-guard"
	}
	if cfg.ReconcileInterval <= 0 {
		cfg.ReconcileInterval = 30 * time.Second
	}
	if cfg.FlushInterval <= 0 {
		cfg.FlushInterval = 2 * time.Second
	}
	profiles := NewBuiltinProfileRegistry()
	tracker := NewIdentityTracker(cfg.HostID, profiles)
	capabilities := ProbeGuardCapabilities("/proc", "/sys")
	if cfg.Capabilities != nil {
		capabilities = *cfg.Capabilities
	}
	manager := &Manager{
		cfg:        cfg,
		scanner:    scanner,
		reporter:   reporter,
		tracker:    tracker,
		reconciler: NewReconciler(tracker),
		normalizer: NewBehaviorNormalizer(cfg.HostID, scanner.BootID(), tracker),
		aggregator: NewAggregator(2 * time.Second),
		spool:      NewPrioritySpool(cfg.SpoolCapacity),
		bundles: NewBundleStoreWithOptions(cfg.StateDir, cfg.HostID, BundleValidationOptions{
			EnforcementAllowed: cfg.EnforcementEnabled,
			FreezeAllowed:      cfg.FreezeEnabled,
			ToolAdapterAllowed: cfg.ToolAdapterEnabled,
		}),
		monitorAllowed:  cfg.BehaviorMonitorEnabled,
		started:         make(map[string]bool),
		startedUnits:    make(map[string]bool),
		startedSessions: make(map[string]bool),
		reconcileReset:  make(chan time.Duration, 1),
		capabilities:    capabilities,
		lastDrift:       make(map[string]string),
		toolAdapter:     cfg.ToolAdapter,
	}
	manager.isolationScan, _ = scanner.(isolationStateScanner)
	manager.actions = newActionExecutor(cfg, tracker, scanner, capabilities)
	manager.actions.report = manager.reportActionResult
	manager.monitorEnabled.Store(cfg.BehaviorMonitorEnabled)
	manager.toolEnabled.Store(false)
	return manager
}

// RebindHostID applies the canonical identity returned by the server before
// discovery starts. Runtime IDs and bundle scope validation must never use the
// temporary ID generated by a fresh local installation.
func (m *Manager) RebindHostID(hostID string) error {
	hostID = strings.TrimSpace(hostID)
	if hostID == "" {
		return errors.New("agent_guard_host_id_invalid")
	}
	m.lifecycleMu.Lock()
	defer m.lifecycleMu.Unlock()
	if m.cancel != nil {
		return errors.New("agent_guard_host_id_rebind_after_start")
	}
	if m.cfg.HostID == hostID {
		return nil
	}
	previous := m.cfg.HostID
	m.cfg.HostID = hostID
	profiles := NewBuiltinProfileRegistry()
	m.tracker = NewIdentityTracker(hostID, profiles)
	m.reconciler = NewReconciler(m.tracker)
	m.normalizer = NewBehaviorNormalizer(hostID, m.scanner.BootID(), m.tracker)
	m.bundles = NewBundleStoreWithOptions(m.cfg.StateDir, hostID, BundleValidationOptions{
		EnforcementAllowed: m.cfg.EnforcementEnabled,
		FreezeAllowed:      m.cfg.FreezeEnabled,
		ToolAdapterAllowed: m.cfg.ToolAdapterEnabled,
	})
	logger.Info("agent_guard_host_identity_rebound",
		zap.String("previous_host_id", previous),
		zap.String("host_id", hostID))
	return nil
}

func (m *Manager) Start(ctx context.Context) error {
	if !m.cfg.Enabled {
		logger.Info("agent_guard_disabled", zap.String("host_id", m.cfg.HostID))
		return nil
	}
	if m.cfg.ToolAdapterEnabled && m.toolAdapter == nil && m.cfg.ToolSourceManifest != "" {
		adapter, err := LoadTrustedToolAdapter(m.cfg.ToolSourceManifest)
		if err != nil {
			return err
		}
		m.toolAdapter = adapter
	}
	var loadedBundle *Bundle
	if bundle, err := m.bundles.Load(); err == nil {
		loadedBundle = &bundle
		m.cfg.ReconcileInterval = time.Duration(bundle.Defaults.ReconcileIntervalSeconds) * time.Second
		m.monitorEnabled.Store(m.monitorAllowed && bundle.Defaults.BehaviorMonitorEnabled)
		m.toolEnabled.Store(m.cfg.ToolAdapterEnabled && bundle.Defaults.ToolAdapterEnabled &&
			m.toolAdapter != nil && m.cfg.ToolHookSocket != "")
		logger.Info("agent_guard_last_known_good_loaded",
			zap.String("host_id", m.cfg.HostID),
			zap.Int64("bundle_version", bundle.BundleVersion),
			zap.String("bundle_digest", bundle.Digest))
	} else if !errors.Is(err, os.ErrNotExist) {
		logger.Warn("agent_guard_last_known_good_load_failed",
			zap.String("host_id", m.cfg.HostID),
			zap.String("error_code", errorCode(err)))
	}
	if err := m.reconcileOnce(); err != nil {
		return err
	}
	toolStatus, toolReason := "ready", ""
	if !m.toolEnabled.Load() {
		toolStatus, toolReason = "tool_semantics_unobservable", "trusted_tool_source_not_enabled"
	}
	m.queueStatusEvent("agent_guard_tool_adapter_status", map[string]any{
		"schema": GuardSchemaV1, "status": toolStatus, "reason": toolReason,
		"occurred_at": time.Now().UTC(),
	}, "info")
	if loadedBundle != nil {
		compiled, err := CompileKernelPolicy(*loadedBundle)
		if err != nil {
			return err
		}
		if err := m.applyCompiledKernelPolicy(*loadedBundle, compiled); err != nil {
			return err
		}
	}
	if err := m.setToolIngressDesired(m.toolEnabled.Load()); err != nil {
		return err
	}
	logger.Info("agent_guard_started",
		zap.String("host_id", m.cfg.HostID),
		zap.Bool("behavior_monitor_enabled", m.monitorEnabled.Load()),
		zap.String("coverage", string(m.currentEnforcementCoverage())),
		zap.Bool("namespace_read", m.capabilities.NamespaceRead),
		zap.Bool("mountinfo_read", m.capabilities.MountInfoRead),
		zap.Bool("bpf_lsm", m.capabilities.BPFLSM),
		zap.Bool("enforcement_enabled", m.cfg.EnforcementEnabled),
		zap.Bool("freeze_enabled", m.cfg.FreezeEnabled),
		zap.Int("supported_monitor_hooks", len(m.capabilities.SupportedHooks)),
		zap.Int("degraded_reason_count", len(m.capabilities.DegradedReasons)),
		zap.Int("reconcile_interval_seconds", int(m.cfg.ReconcileInterval.Seconds())))
	runCtx, cancel := context.WithCancel(ctx)
	m.cancel = cancel
	m.wg.Add(1)
	go func() {
		defer m.wg.Done()
		m.run(runCtx)
	}()
	return nil
}

func (m *Manager) Stop() {
	m.monitorEnabled.Store(false)
	m.toolEnabled.Store(false)
	_ = m.setToolIngressDesired(false)
	if m.cancel != nil {
		m.cancel()
		m.wg.Wait()
	}
}

func (m *Manager) run(ctx context.Context) {
	reconcileTicker := time.NewTicker(m.cfg.ReconcileInterval)
	flushTicker := time.NewTicker(m.cfg.FlushInterval)
	defer reconcileTicker.Stop()
	defer flushTicker.Stop()
	defer logger.Info("agent_guard_stopped", zap.String("host_id", m.cfg.HostID))
	for {
		select {
		case <-ctx.Done():
			m.enqueueAggregates(m.aggregator.Flush(time.Now().Add(m.aggregator.window)))
			m.flush()
			return
		case <-reconcileTicker.C:
			if err := m.reconcileOnce(); err != nil {
				logger.Warn("agent_guard_reconcile_failed",
					zap.String("host_id", m.cfg.HostID),
					zap.String("error_code", errorCode(err)))
			}
		case interval := <-m.reconcileReset:
			reconcileTicker.Reset(interval)
		case now := <-flushTicker.C:
			m.enqueueAggregates(m.aggregator.Flush(now))
			m.flush()
		}
	}
}

func (m *Manager) ApplyBundle(payload string) error {
	if !m.cfg.Enabled {
		return errors.New("agent_guard_disabled")
	}
	candidateVersion, candidateDigest := bundleIdentity(payload)
	if candidateVersion > 0 {
		m.queueConfigStatus("received", candidateVersion, candidateDigest, "")
		m.queueConfigStatus("validating", candidateVersion, candidateDigest, "")
	}
	bundle, err := m.bundles.ValidatePayload([]byte(payload))
	if err != nil {
		code := errorCode(err)
		if candidateVersion > 0 {
			m.queueConfigStatus("rejected", candidateVersion, candidateDigest, code)
		}
		logger.Warn("agent_guard_bundle_rejected",
			zap.String("host_id", m.cfg.HostID),
			zap.String("error_code", code))
		return err
	}
	compiled, err := CompileKernelPolicy(bundle)
	if err != nil {
		code := errorCode(err)
		m.queueConfigStatus("rejected", bundle.BundleVersion, bundle.Digest, code)
		return err
	}
	previous, previousErr := m.bundles.Load()
	if err := m.applyCompiledKernelPolicy(bundle, compiled); err != nil {
		code := errorCode(err)
		m.queueConfigStatus("rejected", bundle.BundleVersion, bundle.Digest, code)
		logger.Warn("agent_guard_kernel_policy_apply_failed",
			zap.String("host_id", m.cfg.HostID),
			zap.Int64("bundle_version", bundle.BundleVersion),
			zap.String("error_code", code))
		return err
	}
	previousToolEnabled := m.toolEnabled.Load()
	desiredToolEnabled := m.cfg.ToolAdapterEnabled && bundle.Defaults.ToolAdapterEnabled &&
		m.toolAdapter != nil && m.cfg.ToolHookSocket != ""
	if desiredToolEnabled {
		if err := m.setToolIngressDesired(true); err != nil {
			if previousErr == nil {
				if rollback, compileErr := CompileKernelPolicy(previous); compileErr == nil {
					_ = m.applyCompiledKernelPolicy(previous, rollback)
				}
			}
			return err
		}
	}
	bundle, err = m.bundles.CommitValidated(bundle)
	if err != nil {
		_ = m.setToolIngressDesired(previousToolEnabled)
		if previousErr == nil {
			if rollback, compileErr := CompileKernelPolicy(previous); compileErr == nil {
				_ = m.applyCompiledKernelPolicy(previous, rollback)
			}
		}
		code := errorCode(err)
		m.queueConfigStatus("rejected", candidateVersion, candidateDigest, code)
		return err
	}
	if bundle.Defaults.ReconcileIntervalSeconds > 0 {
		interval := time.Duration(bundle.Defaults.ReconcileIntervalSeconds) * time.Second
		select {
		case m.reconcileReset <- interval:
		default:
			select {
			case <-m.reconcileReset:
			default:
			}
			m.reconcileReset <- interval
		}
	}
	m.monitorEnabled.Store(m.monitorAllowed && bundle.Defaults.BehaviorMonitorEnabled)
	m.toolEnabled.Store(desiredToolEnabled)
	if err := m.setToolIngressDesired(desiredToolEnabled); err != nil {
		return err
	}
	m.actions.SetFreezeTimeout(time.Duration(bundle.Defaults.FreezeTimeoutSeconds) * time.Second)
	m.queueConfigStatus("applied", bundle.BundleVersion, bundle.Digest, "")
	logger.Info("agent_guard_bundle_applied",
		zap.String("host_id", m.cfg.HostID),
		zap.Int64("bundle_version", bundle.BundleVersion),
		zap.String("bundle_digest", bundle.Digest),
		zap.Int("profile_count", len(bundle.Profiles)),
		zap.Int("policy_count", len(bundle.Policies)))
	return nil
}

func bundleIdentity(payload string) (int64, string) {
	var identity struct {
		BundleVersion int64  `json:"bundle_version"`
		Digest        string `json:"digest"`
	}
	if err := json.Unmarshal([]byte(payload), &identity); err != nil {
		return 0, ""
	}
	if len(identity.Digest) > 80 {
		identity.Digest = ""
	}
	return identity.BundleVersion, identity.Digest
}

func (m *Manager) CurrentBundle() (Bundle, error) {
	return m.bundles.Load()
}

func (m *Manager) Tracker() *IdentityTracker {
	return m.tracker
}

func (m *Manager) SetKernelPolicyApplier(
	applier func(CompiledKernelPolicy, []KernelSubject) error,
) {
	m.kernelPolicyMu.Lock()
	m.kernelApply = applier
	m.kernelPolicyMu.Unlock()
}

func (m *Manager) applyCompiledKernelPolicy(bundle Bundle, compiled CompiledKernelPolicy) error {
	m.kernelPolicyMu.RLock()
	applier := m.kernelApply
	m.kernelPolicyMu.RUnlock()
	if !bundle.Defaults.EnforcementEnabled {
		compiled = CompiledKernelPolicy{BundleVersion: bundle.BundleVersion, BundleDigest: bundle.Digest}
	}
	if !m.cfg.EnforcementEnabled {
		m.kernelPolicyMu.Lock()
		m.kernelPolicy = compiled
		m.kernelPolicyMu.Unlock()
		return nil
	}
	if bundle.Defaults.EnforcementEnabled && !m.capabilities.BPFLSM {
		logger.Warn("agent_guard_enforcement_unavailable",
			zap.String("host_id", m.cfg.HostID),
			zap.Int64("bundle_version", bundle.BundleVersion),
			zap.String("error_code", "bpf_lsm_unavailable"))
		m.kernelPolicyMu.Lock()
		m.kernelPolicy = compiled
		m.kernelPolicyMu.Unlock()
		return nil
	}
	if applier == nil {
		if bundle.Defaults.EnforcementEnabled {
			return errors.New("agent_guard_lsm_applier_unavailable")
		}
		return nil
	}
	if err := applier(compiled, m.tracker.KernelSubjects(compiled)); err != nil {
		return err
	}
	m.kernelPolicyMu.Lock()
	m.kernelPolicy = compiled
	m.kernelPolicyMu.Unlock()
	return nil
}

func (m *Manager) syncKernelSubjects() {
	m.kernelPolicyMu.RLock()
	compiled := m.kernelPolicy
	applier := m.kernelApply
	m.kernelPolicyMu.RUnlock()
	if applier == nil || compiled.BundleVersion == 0 || !m.capabilities.BPFLSM {
		return
	}
	if err := applier(compiled, m.tracker.KernelSubjects(compiled)); err != nil {
		logger.Warn("agent_guard_lsm_subject_sync_failed",
			zap.String("host_id", m.cfg.HostID),
			zap.Int64("bundle_version", compiled.BundleVersion),
			zap.String("error_code", errorCode(err)))
	}
}

func (m *Manager) Capabilities() GuardCapabilities {
	return m.capabilities
}

func (m *Manager) ObserveTrustedToolPayload(payload []byte) (BehaviorEvent, error) {
	if !m.cfg.Enabled || !m.monitorEnabled.Load() || !m.toolEnabled.Load() || m.toolAdapter == nil {
		return BehaviorEvent{}, errors.New("tool_semantics_unobservable")
	}
	decoder := json.NewDecoder(strings.NewReader(string(payload)))
	decoder.DisallowUnknownFields()
	var input TrustedToolEvent
	if err := decoder.Decode(&input); err != nil {
		return BehaviorEvent{}, errors.New("agent_guard_tool_event_json_invalid")
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return BehaviorEvent{}, errors.New("agent_guard_tool_event_json_invalid")
	}
	verified, err := m.toolAdapter.Verify(input)
	if err != nil {
		return BehaviorEvent{}, err
	}
	process, err := m.scanner.ReadPID(input.PID)
	if err != nil || process.Identity != (ProcessIdentity{PID: input.PID, StartTicks: input.StartTicks}) {
		return BehaviorEvent{}, errors.New("agent_guard_tool_process_identity_stale")
	}
	subject, ok := m.tracker.Attribute(process)
	if !ok || subject.Confidence != ConfidenceConfirmed {
		return BehaviorEvent{}, errors.New("agent_guard_tool_process_not_confirmed")
	}
	session, sessionChanged := m.tracker.ObserveTrustedSession(subject, verified.Source.SourceType, verified.CorrelationHash)
	if session.SessionID == "" {
		return BehaviorEvent{}, errors.New("agent_guard_tool_session_unavailable")
	}
	m.queueTrustedSessionStatus(session, sessionChanged)
	parentEventID := ""
	if link, exists := m.toolAdapter.Lookup(process.Identity); exists &&
		link.CorrelationHash == verified.CorrelationHash && link.ToolCallID == input.ToolCallID {
		parentEventID = link.ToolEventID
	}
	attributes := map[string]any{"tool_call_id": input.ToolCallID}
	if input.ProcessEventID != "" {
		attributes["process_event_id"] = input.ProcessEventID
	}
	if len(input.ResourceEventIDs) > 0 {
		attributes["resource_event_ids"] = append([]string(nil), input.ResourceEventIDs...)
	}
	remoteCoverage := string(CoverageRemoteUnobservable)
	if verified.Remote != nil {
		attributes["remote_host_id"] = verified.Remote.RemoteHostID
		attributes["remote_execution_unit_id"] = verified.Remote.RemoteExecutionUnitID
		attributes["remote_sensor_event_id"] = verified.Remote.EventID
	}
	outcome := OutcomeUnknown
	if input.Operation == ToolEventCompleted {
		outcome = OutcomeSuccess
	} else if input.Operation == ToolEventFailed {
		outcome = OutcomeFailed
	}
	event, accepted := m.observeRawEvent(RawBehavior{
		EventID: input.EventID, EventType: "agent_tool_call", SessionID: session.SessionID,
		CorrelationID: verified.CorrelationHash, ParentEventID: parentEventID,
		OccurredAt: input.OccurredAt, Category: CategoryTool, Operation: input.Operation,
		Outcome: outcome, Process: process,
		Resource: Resource{Type: "tool", Identity: input.ToolName, Attributes: attributes},
		Source:   verified.Source.SourceType, Sensor: verified.Source.SourceID, Visibility: "complete",
		Decision: DecisionAudit, Severity: "info",
		Evidence: map[string]any{
			"trusted_proof":          verified.Proof,
			"correlation_token_hash": verified.CorrelationHash,
			"remote_coverage":        remoteCoverage,
		},
	})
	if !accepted {
		return BehaviorEvent{}, errors.New("agent_guard_tool_event_unattributed")
	}
	if input.Operation == ToolEventStarted {
		m.toolAdapter.Bind(process.Identity, toolCorrelationLink{
			CorrelationHash: verified.CorrelationHash, ToolEventID: event.EventID,
			ToolCallID: input.ToolCallID, SessionID: session.SessionID,
			ExpiresAt: input.OccurredAt.Add(30 * time.Minute),
		})
	} else {
		m.toolAdapter.Complete(process.Identity)
	}
	return event, nil
}

func (m *Manager) setToolIngressDesired(enabled bool) error {
	m.toolIngressMu.Lock()
	if !enabled {
		ingress := m.toolIngress
		m.toolIngress = nil
		m.toolIngressMu.Unlock()
		if ingress != nil {
			ingress.Stop()
		}
		return nil
	}
	defer m.toolIngressMu.Unlock()
	if m.toolIngress != nil {
		return nil
	}
	ingress, err := StartToolHookReceiver(
		m.cfg.ToolHookSocket, m.toolAdapter.SocketPolicy(),
		m.toolAdapter.AuthorizePeer, m.ObserveTrustedToolPayload,
	)
	if err != nil {
		return err
	}
	m.toolIngress = ingress
	logger.Info("agent_guard_tool_hook_started",
		zap.String("host_id", m.cfg.HostID),
		zap.String("socket_path", m.cfg.ToolHookSocket))
	return nil
}

// ExecuteAgentGuardAction handles only the V6.2 UUID-scoped Agent Guard action
// family. Real cgroup paths and PID/start_ticks identities are always resolved
// from the local registry by ActionExecutor.
func (m *Manager) ExecuteAgentGuardAction(
	ctx context.Context,
	commandID, action, target, _ string,
) (ActionResult, error) {
	if !m.cfg.Enabled {
		result := ActionResult{CommandID: commandID, Action: action, Status: ActionStatusFailed, ErrorCode: "agent_guard_disabled"}
		m.reportActionResult(result)
		return result, errors.New(result.ErrorCode)
	}
	result, err := m.actions.Execute(ctx, commandID, action, target)
	m.reportActionResult(result)
	return result, err
}

func (m *Manager) reportActionResult(result ActionResult) {
	if result.ActionID == "" {
		result.ActionID = actionID(result.CommandID, result.Action, result.ExecutionUnitID, result.InstanceID)
	}
	body := map[string]any{
		"schema":            GuardSchemaV1,
		"action_id":         result.ActionID,
		"command_id":        result.CommandID,
		"action":            result.Action,
		"instance_id":       result.InstanceID,
		"execution_unit_id": result.ExecutionUnitID,
		"status":            result.Status,
		"method":            result.Method,
		"degraded":          result.Degraded,
		"auto_resume":       result.AutoResume,
		"executed":          result.Executed,
		"state_changed":     result.StateChanged,
		"error_code":        result.ErrorCode,
		"occurred_at":       time.Now().UTC(),
	}
	severity := "info"
	if result.Status == ActionStatusFailed {
		severity = "high"
	}
	m.queueStatusEvent("agent_guard_action_status", body, severity)
	logger.Info("agent_guard_action_result",
		zap.String("host_id", m.cfg.HostID),
		zap.String("action_id", result.ActionID),
		zap.String("command_id", result.CommandID),
		zap.String("action", result.Action),
		zap.String("instance_id", result.InstanceID),
		zap.String("execution_unit_id", result.ExecutionUnitID),
		zap.String("status", result.Status),
		zap.String("method", result.Method),
		zap.Bool("degraded", result.Degraded),
		zap.Bool("executed", result.Executed),
		zap.Bool("state_changed", result.StateChanged),
		zap.String("error_code", result.ErrorCode))
}

func actionID(commandID, action, unitID, instanceID string) string {
	trimmed := strings.TrimSpace(commandID)
	for _, candidate := range []string{
		trimmed,
		strings.TrimPrefix(trimmed, "AG-GUARD-"),
	} {
		if parsed, err := uuid.Parse(candidate); err == nil && parsed != uuid.Nil {
			return parsed.String()
		}
	}
	if trimmed == "" {
		return uuid.NewString()
	}
	return stableID("action", trimmed, action, unitID, instanceID)
}

func (m *Manager) AttachContainer(instanceID string, info ContainerCgroup) (ExecutionUnit, error) {
	unit, err := m.tracker.AttachContainer(instanceID, info)
	if err != nil {
		return ExecutionUnit{}, err
	}
	m.queuePendingLifecycles()
	return unit, nil
}

func (m *Manager) ObserveRaw(raw RawBehavior) bool {
	_, ok := m.observeRawEvent(raw)
	return ok
}

func (m *Manager) observeRawEvent(raw RawBehavior) (BehaviorEvent, bool) {
	if !m.cfg.Enabled || !m.monitorEnabled.Load() {
		return BehaviorEvent{}, false
	}
	if raw.CorrelationID == "" && m.toolEnabled.Load() && m.toolAdapter != nil {
		if link, ok := m.toolAdapter.Lookup(raw.Process.Identity); ok {
			raw.SessionID = link.SessionID
			raw.CorrelationID = link.CorrelationHash
			raw.ParentEventID = link.ToolEventID
			if raw.Evidence == nil {
				raw.Evidence = make(map[string]any)
			}
			raw.Evidence["correlation_token_hash"] = link.CorrelationHash
			raw.Evidence["tool_call_id"] = link.ToolCallID
		}
	}
	event, ok := m.normalizer.Normalize(raw)
	if !ok {
		return BehaviorEvent{}, false
	}
	m.enqueueAggregates(m.aggregator.Add(event))
	return event, true
}

func (m *Manager) ObserveEventMap(eventMap map[string]any) bool {
	if !m.cfg.Enabled || !m.monitorEnabled.Load() {
		return false
	}
	pid := uint32(numberValue(eventMap["pid"]))
	if pid == 0 {
		return false
	}
	process, err := m.scanner.ReadPID(pid)
	if err != nil {
		return false
	}
	eventType := stringValue(eventMap["event_type"])
	switch eventType {
	case "process_fork":
		parent, err := m.scanner.ReadPID(process.PPID)
		if err == nil {
			m.tracker.OnFork(parent.Identity, process)
			if m.toolAdapter != nil {
				m.toolAdapter.OnFork(parent.Identity, process.Identity)
			}
		}
	case "process_exec":
		m.tracker.OnExec(process)
	}
	if eventType == "process_fork" || eventType == "process_exec" {
		m.syncKernelSubjects()
		// A controller can be confirmed during exec attribution, before the
		// periodic reconcile loop. Queue its dependency chain now so Kafka
		// observes lifecycle state before the first behavior for that scope.
		m.queuePendingLifecycles()
	}
	if eventType == "agent_guard_syscall" {
		return m.observeGuardSemanticEvent(eventMap, process)
	}
	category, operation := mapBehaviorOperation(eventType, eventMap)
	if category == "" {
		return false
	}
	outcome := OutcomeSuccess
	if status := stringValue(eventMap["connect_status"]); status == "failed" {
		outcome = OutcomeFailed
	}
	resource := Resource{Type: string(category)}
	switch category {
	case CategoryFile:
		resource.Type = "file"
		resource.Identity = stringValue(eventMap["file_path"])
	case CategoryNetwork:
		resource.Type = "network"
		resource.Identity = stringValue(eventMap["remote_addr"])
		resource.Attributes = map[string]any{
			"destination_ip":   stringValue(eventMap["dst_ip"]),
			"destination_port": numberValue(eventMap["dst_port"]),
			"protocol":         stringValue(eventMap["network_transport"]),
			"content_observed": false,
		}
	case CategoryProcess:
		resource.Type = "process"
		resource.Identity = process.Exe
	}
	normalized, accepted := m.observeRawEvent(RawBehavior{
		EventID:    stringValue(eventMap["event_id"]),
		OccurredAt: time.Now().UTC(),
		Category:   category,
		Operation:  operation,
		Outcome:    outcome,
		Process:    process,
		Argv:       strings.Fields(stringValue(eventMap["commandline"])),
		Resource:   resource,
		Source:     "ebpf",
		Sensor:     eventType,
		Visibility: visibilityForEvent(eventMap),
	})
	if !accepted {
		return false
	}
	if category == CategoryFile {
		m.observeEscapeViolation(GuardAttempt{
			EventID: normalized.EventID, Category: category, Operation: operation,
			Target: resource.Identity, ReturnCode: numberValue(eventMap["return_code"]),
		}, process, normalized)
	}
	return true
}

func (m *Manager) observeGuardSemanticEvent(eventMap map[string]any, process ProcessSnapshot) bool {
	category := Category(stringValue(eventMap["security_category"]))
	switch category {
	case CategoryProcess, CategoryNetwork, CategoryIdentity, CategoryKernel, CategoryIsolation:
	default:
		return false
	}
	operation := stringValue(eventMap["security_operation"])
	if operation == "" {
		return false
	}
	subject, ok := m.tracker.Attribute(process)
	if !ok {
		return false
	}
	unit, ok := m.tracker.Unit(subject.UnitID)
	if !ok {
		return false
	}
	baseline := unit.IsolationBaseline
	actual := unit.IsolationActual
	if m.isolationScan != nil {
		if observed, err := m.isolationScan.ReadIsolation(process.Identity.PID); err == nil {
			actual = observed
			if baseline.CapturedAt.IsZero() {
				baseline = observed
			}
			unit, _ = m.tracker.UpdateUnitIsolation(unit.UnitID, observed, m.capabilities)
		}
	}
	returnCode := numberValue(eventMap["return_code"])
	outcome := OutcomeSuccess
	errno := int32(0)
	if returnCode < 0 {
		outcome = OutcomeFailed
		if returnCode >= -1<<31 {
			errno = int32(-returnCode)
		}
	}
	target := stringValue(eventMap["security_target"])
	secondary := stringValue(eventMap["security_secondary"])
	diff := DiffIsolationState(baseline, actual)
	evidence := map[string]any{
		"syscall":       operation,
		"target":        target,
		"secondary":     secondary,
		"return_code":   returnCode,
		"baseline":      baseline,
		"actual":        actual,
		"diff":          diff,
		"state_changed": diff.StateChanged,
		"identity_before": map[string]any{
			"uid": numberValue(eventMap["uid"]),
			"gid": numberValue(eventMap["gid"]),
		},
		"identity_after": map[string]any{
			"uid": process.UID,
			"gid": process.GID,
		},
	}
	decision := DecisionAudit
	switch stringValue(eventMap["security_decision"]) {
	case string(DecisionDeny):
		decision = DecisionDeny
	case string(DecisionDenyAndFreeze):
		decision = DecisionDenyAndFreeze
	}
	severity := "info"
	if decision == DecisionDeny || decision == DecisionDenyAndFreeze {
		severity = "critical"
	}
	normalized, accepted := m.observeRawEvent(RawBehavior{
		EventID:             stringValue(eventMap["event_id"]),
		OccurredAt:          time.Now().UTC(),
		OccurredMonotonicNS: uint64(max(numberValue(eventMap["timestamp_ns"]), 0)),
		Category:            category,
		Operation:           operation + "_attempt",
		Outcome:             outcome,
		Errno:               errno,
		Process:             process,
		Argv:                process.Argv,
		Resource: Resource{
			Type: string(category), Identity: target,
			Attributes: map[string]any{
				"syscall": operation, "secondary_target": secondary,
				"return_code": returnCode, "content_observed": false,
			},
		},
		Source: "ebpf", Sensor: "agent_guard_syscall",
		Visibility: visibilityForEvent(eventMap), Decision: decision,
		Severity: severity,
		Isolation: map[string]any{
			"unit_type": unit.Type, "baseline_fingerprint": baseline.Fingerprint(),
			"actual_fingerprint": actual.Fingerprint(),
			"completeness":       actual.Completeness(),
		},
		Evidence: evidence,
	})
	if !accepted {
		return false
	}
	if decision == DecisionDenyAndFreeze &&
		normalized.AttributionConfidence == ConfidenceConfirmed &&
		normalized.ExecutionUnitID != "" {
		commandID := "AG-GUARD-" + uuid.NewString()
		unitID := normalized.ExecutionUnitID
		go func() {
			result, err := m.actions.Execute(context.Background(), commandID, ActionFreezeExecutionUnit, unitID)
			m.reportActionResult(result)
			if err != nil {
				logger.Warn("agent_guard_local_freeze_failed",
					zap.String("host_id", m.cfg.HostID),
					zap.String("execution_unit_id", unitID),
					zap.String("command_id", commandID),
					zap.String("error_code", errorCode(err)))
			}
		}()
	}
	attempt := GuardAttempt{
		EventID: normalized.EventID, Category: category, Operation: operation,
		Target: target, SecondaryTarget: secondary,
		TargetPID:  uint32(numberValue(eventMap["security_arg1"])),
		ReturnCode: returnCode, Baseline: baseline, Actual: actual,
	}
	if _, exists := eventMap["uid"]; exists {
		attempt.BeforeUID = uint32(numberValue(eventMap["uid"]))
		attempt.BeforeUIDVisible = true
	}
	if kind, _, ok := parseNamespaceIdentity(target); ok {
		attempt.TargetNamespace = kind
	}
	m.observeEscapeViolation(attempt, process, normalized)
	return true
}

func (m *Manager) observeEscapeViolation(
	attempt GuardAttempt,
	process ProcessSnapshot,
	parent BehaviorEvent,
) bool {
	subject, ok := m.tracker.Attribute(process)
	if !ok {
		return false
	}
	unit, ok := m.tracker.Unit(subject.UnitID)
	if !ok {
		return false
	}
	if attempt.Baseline.CapturedAt.IsZero() {
		attempt.Baseline = unit.IsolationBaseline
	}
	if attempt.Actual.CapturedAt.IsZero() {
		attempt.Actual = unit.IsolationActual
	}
	if attempt.Operation == "ptrace" && attempt.TargetPID > 0 {
		target, err := m.scanner.ReadPID(attempt.TargetPID)
		if err == nil {
			if targetSubject, attributed := m.tracker.Attribute(target); attributed &&
				targetSubject.UnitID == subject.UnitID {
				attempt.TargetPID = 0
			}
		}
	}
	attempt.EvidenceEventIDs = []string{parent.EventID}
	violation, detected := DetectEscapeAttempt(attempt)
	if !detected {
		return false
	}
	evidence := map[string]any{
		"rule":               violation.Rule,
		"operation":          violation.Operation,
		"target":             violation.Target,
		"baseline":           violation.Baseline,
		"actual":             violation.Actual,
		"diff":               violation.Diff,
		"state_changed":      violation.StateChanged,
		"return_code":        violation.ReturnCode,
		"evidence_event_ids": violation.EvidenceEventIDs,
	}
	_, accepted := m.observeRawEvent(RawBehavior{
		OccurredAt: time.Now().UTC(), Category: attempt.Category,
		Operation: attempt.Operation + "_violation", Outcome: parent.Outcome,
		Process: process, Argv: process.Argv,
		Resource: Resource{
			Type: "escape_target", Identity: violation.Target,
			Classification: violation.Rule,
		},
		Source: "agent_guard", Sensor: "escape_evaluator",
		Visibility: parent.Collection.Visibility,
		EventType:  "agent_sandbox_violation", Decision: violation.Decision,
		Severity: violation.Severity, RuleID: violation.Rule,
		Isolation: map[string]any{
			"unit_type": unit.Type, "baseline": violation.Baseline,
			"actual": violation.Actual, "diff": violation.Diff,
			"completeness": violation.Actual.Completeness(),
		},
		Evidence: evidence,
	})
	if accepted {
		logger.Warn("agent_guard_escape_would_deny",
			zap.String("host_id", m.cfg.HostID),
			zap.String("instance_id", subject.InstanceID),
			zap.String("execution_unit_id", subject.UnitID),
			zap.String("rule_id", violation.Rule),
			zap.String("decision", string(violation.Decision)),
			zap.Bool("state_changed", violation.StateChanged))
	}
	return accepted
}

func (m *Manager) reconcileIsolation(processes []ProcessSnapshot) {
	if m.isolationScan == nil {
		return
	}
	states := make(map[ProcessIdentity]IsolationState)
	for _, process := range processes {
		if _, ok := m.tracker.LookupProcess(process.Identity); !ok {
			continue
		}
		state, err := m.isolationScan.ReadIsolation(process.Identity.PID)
		if err != nil {
			state = unavailableIsolationState("proc_isolation_read_failed")
		}
		states[process.Identity] = state
	}

	controllerStates := make(map[string]IsolationState)
	for _, instance := range m.tracker.Instances() {
		if state, ok := states[instance.Controller]; ok {
			controllerStates[instance.InstanceID] = state
		}
	}
	for _, process := range processes {
		subject, ok := m.tracker.LookupProcess(process.Identity)
		if !ok {
			continue
		}
		instance, ok := m.tracker.Instance(subject.InstanceID)
		if !ok {
			continue
		}
		profile, ok := m.tracker.profiles.Profile(instance.ProfileKey)
		if !ok || profile.SandboxFamily != IsolationLinuxNamespace ||
			!m.tracker.profiles.MatchWorker(instance.ProfileKey, process) {
			continue
		}
		state := states[process.Identity]
		controllerState := controllerStates[instance.InstanceID]
		if namespaceTupleEqual(state, controllerState) {
			continue
		}
		if _, err := m.tracker.AttachNamespace(instance.InstanceID, process, state); err != nil {
			logger.Debug("agent_guard_namespace_unit_discovery_skipped",
				zap.String("instance_id", instance.InstanceID),
				zap.String("error_code", errorCode(err)))
		}
	}

	namespaceUnits := make(map[string]string)
	for _, unit := range m.tracker.Units() {
		if unit.Type == IsolationLinuxNamespace {
			namespaceUnits[unit.InstanceID+"\x00"+namespaceFingerprint(unit.IsolationBaseline)] = unit.UnitID
		}
	}
	for _, process := range processes {
		subject, ok := m.tracker.LookupProcess(process.Identity)
		if !ok {
			continue
		}
		state, ok := states[process.Identity]
		if !ok || len(state.NamespaceInodes) == 0 {
			continue
		}
		if unitID := namespaceUnits[subject.InstanceID+"\x00"+namespaceFingerprint(state)]; unitID != "" {
			m.tracker.AssignProcessToUnit(process, unitID)
		}
	}

	representatives := make(map[string]ProcessSnapshot)
	for _, unit := range m.tracker.Units() {
		if unit.RootProcess.Valid() {
			for _, process := range processes {
				if process.Identity == unit.RootProcess {
					representatives[unit.UnitID] = process
					break
				}
			}
		}
	}
	for _, process := range processes {
		subject, ok := m.tracker.Attribute(process)
		if !ok {
			continue
		}
		if _, exists := representatives[subject.UnitID]; !exists {
			representatives[subject.UnitID] = process
		}
	}
	for unitID, process := range representatives {
		actual, ok := states[process.Identity]
		if !ok {
			actual = unavailableIsolationState("representative_state_missing")
		}
		previous, _ := m.tracker.Unit(unitID)
		updated, hadBaseline := m.tracker.UpdateUnitIsolation(unitID, actual, m.capabilities)
		stateChanged := previous.IsolationActual.Fingerprint() != updated.IsolationActual.Fingerprint()
		if hadBaseline && stateChanged {
			m.lifecycleMu.Lock()
			if m.startedUnits[unitID] {
				m.queueExecutionUnitStatus(updated, "agent_execution_unit_updated")
			}
			m.lifecycleMu.Unlock()
		}
		if hadBaseline && updated.IsolationDiff.StateChanged {
			m.emitIsolationDrift(process, updated)
		} else if !updated.IsolationDiff.StateChanged {
			m.isolationMu.Lock()
			delete(m.lastDrift, unitID)
			m.isolationMu.Unlock()
		}
	}
}

func (m *Manager) emitIsolationDrift(process ProcessSnapshot, unit ExecutionUnit) {
	data, _ := json.Marshal(unit.IsolationDiff)
	digest := stableID("drift", unit.UnitID, string(data))
	m.isolationMu.Lock()
	if m.lastDrift[unit.UnitID] == digest {
		m.isolationMu.Unlock()
		return
	}
	m.lastDrift[unit.UnitID] = digest
	m.isolationMu.Unlock()
	decision := DecisionWouldDeny
	severity := "high"
	if unit.Coverage == CoverageNoIsolation || !dangerousIsolationDrift(unit) {
		decision = DecisionAudit
		severity = "medium"
	}
	_, accepted := m.observeRawEvent(RawBehavior{
		OccurredAt: time.Now().UTC(), Category: CategoryIsolation,
		Operation: "isolation_drift", Outcome: OutcomeUnknown,
		Process: process, Argv: process.Argv,
		Resource: Resource{
			Type: "execution_unit", Identity: unit.UnitID,
			Classification: EscapeRuleIsolationDrift,
		},
		Source: "procfs", Sensor: "isolation_reconciler",
		Visibility: visibilityFromCompleteness(unit.Completeness), EventType: "agent_isolation_drift",
		Decision: decision, Severity: severity, RuleID: EscapeRuleIsolationDrift,
		Isolation: map[string]any{
			"unit_type": unit.Type, "baseline": unit.IsolationBaseline,
			"actual": unit.IsolationActual, "diff": unit.IsolationDiff,
			"completeness": unit.Completeness,
		},
		Evidence: map[string]any{
			"rule": EscapeRuleIsolationDrift, "baseline": unit.IsolationBaseline,
			"actual": unit.IsolationActual, "diff": unit.IsolationDiff,
			"state_changed": unit.IsolationDiff.StateChanged,
		},
	})
	if accepted {
		logger.Warn("agent_guard_isolation_drift_observed",
			zap.String("host_id", m.cfg.HostID),
			zap.String("instance_id", unit.InstanceID),
			zap.String("execution_unit_id", unit.UnitID),
			zap.String("decision", string(decision)),
			zap.Int("changed_dimension_count", len(unit.IsolationDiff.Changes)))
	}
}

func visibilityFromCompleteness(completeness string) string {
	switch completeness {
	case "complete":
		return "complete"
	case "unavailable":
		return "unobservable"
	default:
		return "partial"
	}
}

func dangerousIsolationDrift(unit ExecutionUnit) bool {
	for key := range unit.IsolationDiff.Changes {
		if strings.HasPrefix(key, "namespace.") || key == "cgroup_path" ||
			key == "root_mount" || key == "capabilities.effective_added" {
			return true
		}
	}
	if change, ok := unit.IsolationDiff.Changes["no_new_privs"]; ok &&
		change.Before == true && change.After == false {
		return true
	}
	if change, ok := unit.IsolationDiff.Changes["seccomp_mode"]; ok {
		before, beforeOK := change.Before.(int)
		after, afterOK := change.After.(int)
		return beforeOK && afterOK && after < before
	}
	return false
}

func unavailableIsolationState(reason string) IsolationState {
	state := newIsolationState()
	for _, key := range isolationDimensions {
		state.Availability[key] = EvidenceAvailability{Available: false, Reason: reason}
	}
	return state
}

func namespaceTupleEqual(left, right IsolationState) bool {
	if len(left.NamespaceInodes) == 0 || len(right.NamespaceInodes) == 0 {
		return true
	}
	for _, key := range []string{"mnt", "pid", "user", "net"} {
		if left.NamespaceInodes[key] != right.NamespaceInodes[key] {
			return false
		}
	}
	return true
}

func (m *Manager) reconcileOnce() error {
	processes, err := m.scanner.Scan()
	if err != nil {
		return fmt.Errorf("scan process identities: %w", err)
	}
	stats := m.reconciler.Reconcile(processes)
	m.reconcileIsolation(processes)
	m.lifecycleMu.Lock()
	m.queuePendingLifecyclesLocked()
	m.lifecycleMu.Unlock()
	m.syncKernelSubjects()
	if stats.ProcessLabelsRepaired > 0 || stats.ExpiredLabelsRemoved > 0 || stats.ControllersDiscovered > 0 {
		logger.Info("agent_guard_reconcile_completed",
			zap.String("host_id", m.cfg.HostID),
			zap.Uint64("controllers_discovered", stats.ControllersDiscovered),
			zap.Uint64("process_labels_repaired", stats.ProcessLabelsRepaired),
			zap.Uint64("expired_labels_removed", stats.ExpiredLabelsRemoved))
	}
	return nil
}

func (m *Manager) queuePendingLifecycles() {
	m.lifecycleMu.Lock()
	defer m.lifecycleMu.Unlock()
	m.queuePendingLifecyclesLocked()
}

func (m *Manager) queueTrustedSessionStatus(session BehaviorSession, changed bool) {
	m.lifecycleMu.Lock()
	defer m.lifecycleMu.Unlock()
	if !m.startedSessions[session.SessionID] {
		m.queuePendingLifecyclesLocked()
		return
	}
	if changed {
		m.queueSessionStatus(session, "agent_behavior_session_updated")
	}
}

func (m *Manager) queuePendingLifecyclesLocked() {
	for _, instance := range m.tracker.Instances() {
		if m.started[instance.InstanceID] {
			continue
		}
		m.started[instance.InstanceID] = true
		m.queueInstanceStatus(instance, "agent_instance_started")
		logger.Info("agent_guard_instance_started",
			zap.String("host_id", m.cfg.HostID),
			zap.String("instance_id", instance.InstanceID),
			zap.String("profile_key", instance.ProfileKey),
			zap.Uint32("controller_pid", instance.Controller.PID))
	}
	for _, unit := range m.tracker.Units() {
		if m.startedUnits[unit.UnitID] || !m.started[unit.InstanceID] {
			continue
		}
		m.startedUnits[unit.UnitID] = true
		m.queueExecutionUnitStatus(unit, "agent_execution_unit_started")
		logger.Info("agent_guard_execution_unit_started",
			zap.String("host_id", m.cfg.HostID),
			zap.String("instance_id", unit.InstanceID),
			zap.String("execution_unit_id", unit.UnitID),
			zap.String("unit_type", string(unit.Type)),
			zap.String("coverage", string(unit.Coverage)))
	}
	for _, session := range m.tracker.Sessions() {
		if m.startedSessions[session.SessionID] || !m.started[session.InstanceID] {
			continue
		}
		m.startedSessions[session.SessionID] = true
		m.queueSessionStatus(session, "agent_behavior_session_started")
		logger.Info("agent_guard_behavior_session_started",
			zap.String("host_id", m.cfg.HostID),
			zap.String("instance_id", session.InstanceID),
			zap.String("session_id", session.SessionID),
			zap.String("session_source", session.Source),
			zap.String("session_confidence", string(session.Confidence)))
	}
}

func (m *Manager) enqueueAggregates(events []BehaviorEvent) {
	for _, event := range events {
		priority := priorityForEvent(event)
		if !m.spool.Push(event, priority) {
			stats := m.spool.Stats()
			logger.Warn("agent_guard_spool_event_dropped",
				zap.String("host_id", m.cfg.HostID),
				zap.String("category", string(event.Category)),
				zap.Int("queued", stats.Queued))
		}
	}
}

func (m *Manager) flush() {
	if m.reporter == nil {
		return
	}
	m.statusMu.Lock()
	status := append([]*pb.RuntimeEvent(nil), m.pendingStatus...)
	m.pendingStatus = nil
	m.statusMu.Unlock()
	behaviors := m.spool.PopBatch(128)
	events := make([]*pb.RuntimeEvent, 0, len(status)+len(behaviors))
	events = append(events, status...)
	for _, event := range behaviors {
		events = append(events, behaviorRuntimeEvent(event))
	}
	if len(events) == 0 {
		return
	}
	if err := m.reporter.ReportEvents(events); err != nil {
		m.statusMu.Lock()
		m.pendingStatus = append(status, m.pendingStatus...)
		m.statusMu.Unlock()
		for _, event := range behaviors {
			m.spool.Push(event, priorityForEvent(event))
		}
		logger.Warn("agent_guard_report_deferred",
			zap.String("host_id", m.cfg.HostID),
			zap.Int("event_count", len(events)),
			zap.String("error_code", errorCode(err)))
	}
}

func (m *Manager) queueConfigStatus(status string, version int64, digest, code string) {
	body := map[string]any{
		"schema": GuardSchemaV1, "status": status, "bundle_version": version,
		"digest": digest, "error_code": code, "occurred_at": time.Now().UTC(),
		"coverage_level": m.currentEnforcementCoverage(),
		"capabilities":   m.capabilities,
	}
	m.queueStatusEvent("agent_guard_config_status", body, "info")
}

func (m *Manager) currentEnforcementCoverage() CoverageLevel {
	m.kernelPolicyMu.RLock()
	policy := m.kernelPolicy
	m.kernelPolicyMu.RUnlock()
	if m.cfg.EnforcementEnabled && m.capabilities.BPFLSM &&
		(len(policy.PathRules) > 0 || len(policy.EscapeRules) > 0) {
		return CoverageFullEnforcement
	}
	return CoverageMonitorOnly
}

func (m *Manager) queueInstanceStatus(instance RuntimeInstance, eventType string) {
	body := map[string]any{
		"schema":                 GuardSchemaV1,
		"instance_id":            instance.InstanceID,
		"asset_id":               instance.AssetID,
		"profile_key":            instance.ProfileKey,
		"profile_version":        instance.ProfileVersion,
		"agent_type":             instance.AgentType,
		"display_name":           instance.DisplayName,
		"controller_pid":         instance.Controller.PID,
		"controller_start_ticks": instance.Controller.StartTicks,
		"controller_exe":         RedactString(instance.ControllerExe),
		"run_uid":                instance.RunUID,
		"detection_confidence":   instance.Confidence,
		"status":                 instance.Status,
		"coverage_level":         instance.Coverage,
		"coverage_reasons":       coverageReasons(instance.Coverage),
		"first_seen_at":          instance.FirstSeenAt,
		"last_seen_at":           instance.LastSeenAt,
		"occurred_at":            time.Now().UTC(),
	}
	m.queueStatusEvent(eventType, body, "info")
}

func (m *Manager) queueExecutionUnitStatus(unit ExecutionUnit, eventType string) {
	baseline := redactIsolationState(unit.IsolationBaseline)
	actual := redactIsolationState(unit.IsolationActual)
	diff := redactIsolationDiff(unit.IsolationDiff, 0)
	body := map[string]any{
		"schema":             GuardSchemaV1,
		"execution_unit_id":  unit.UnitID,
		"instance_id":        unit.InstanceID,
		"unit_type":          unit.Type,
		"fingerprint":        stableID("fingerprint", m.cfg.HostID, unit.InstanceID, unit.UnitID),
		"cgroup_path":        RedactString(unit.CgroupPath),
		"container_id":       unit.ContainerID,
		"container_runtime":  unit.ContainerRuntime,
		"coverage_level":     unit.Coverage,
		"coverage_reasons":   appendCoverageReasons(unit.Coverage, unit.IsolationActual),
		"capabilities":       unit.Capabilities,
		"isolation_baseline": baseline,
		"isolation_actual":   actual,
		"isolation_diff":     diff,
		"completeness":       unit.Completeness,
		"status":             unit.Status,
		"first_seen_at":      unit.FirstSeenAt,
		"last_seen_at":       unit.LastSeenAt,
		"occurred_at":        time.Now().UTC(),
	}
	if unit.RootProcess.Valid() {
		body["root_pid"] = unit.RootProcess.PID
		body["root_start_ticks"] = unit.RootProcess.StartTicks
	}
	m.queueStatusEvent(eventType, body, "info")
}

func (m *Manager) queueSessionStatus(session BehaviorSession, eventType string) {
	body := map[string]any{
		"schema":                 GuardSchemaV1,
		"session_id":             session.SessionID,
		"instance_id":            session.InstanceID,
		"execution_unit_id":      unitIDForSession(m.tracker.Units(), session.SessionID),
		"source":                 session.Source,
		"confidence":             session.Confidence,
		"correlation_token_hash": session.CorrelationTokenHash,
		"status":                 session.Status,
		"completeness":           map[string]any{},
		"started_at":             session.FirstSeenAt,
		"last_seen_at":           session.LastSeenAt,
		"occurred_at":            time.Now().UTC(),
	}
	m.queueStatusEvent(eventType, body, "info")
}

func unitIDForSession(units []ExecutionUnit, sessionID string) string {
	for _, unit := range units {
		if unit.SessionID == sessionID {
			return unit.UnitID
		}
	}
	return ""
}

func coverageReasons(level CoverageLevel) []string {
	switch level {
	case CoverageNoIsolation:
		return []string{"backend_no_isolation"}
	case CoverageRemoteUnobservable:
		return []string{"remote_sensor_unavailable"}
	case CoverageDegraded:
		return []string{"p1_monitor_only", "isolation_evidence_partial"}
	default:
		return []string{"p1_monitor_only"}
	}
}

func behaviorCoverage(level CoverageLevel) CoverageLevel {
	if level == CoverageDegraded {
		return CoverageMonitorOnly
	}
	return level
}

func (m *Manager) queueStatusEvent(eventType string, body map[string]any, severity string) {
	data, err := json.Marshal(body)
	if err != nil {
		return
	}
	event := &pb.RuntimeEvent{
		EventId: stableID(eventType, m.cfg.HostID, time.Now().UnixNano()),
		HostId:  m.cfg.HostID, Timestamp: time.Now().UnixMilli(),
		EventType: eventType, Severity: severity, EventDataJson: string(data),
	}
	m.statusMu.Lock()
	m.pendingStatus = append(m.pendingStatus, event)
	m.statusMu.Unlock()
}

func behaviorRuntimeEvent(event BehaviorEvent) *pb.RuntimeEvent {
	return &pb.RuntimeEvent{
		EventId: validProtoString(event.EventID), HostId: validProtoString(event.HostID),
		Timestamp: event.OccurredAt.UnixMilli(), EventType: validProtoString(event.EventType),
		ProcessName: validProtoString(filepath.Base(event.Actor.Exe)), Pid: int32(event.Actor.PID),
		Ppid: int32(event.Actor.PPID), Uid: int32(event.Actor.UID),
		CommandLine: validProtoString(strings.Join(event.Actor.Argv, " ")),
		FilePath:    validProtoString(behaviorFilePath(event)), RemoteAddr: validProtoString(behaviorRemoteAddr(event)),
		Severity: validProtoString(event.Severity), EventDataJson: validProtoString(event.MustJSON()),
	}
}

func validProtoString(value string) string {
	return strings.ToValidUTF8(value, "\uFFFD")
}

func behaviorFilePath(event BehaviorEvent) string {
	if event.Category == CategoryFile {
		return event.Resource.Identity
	}
	return ""
}

func behaviorRemoteAddr(event BehaviorEvent) string {
	if event.Category == CategoryNetwork {
		return event.Resource.Identity
	}
	return ""
}

func mapBehaviorOperation(eventType string, eventMap map[string]any) (Category, string) {
	switch eventType {
	case "process_exec":
		return CategoryProcess, "exec"
	case "process_fork":
		return CategoryProcess, "fork"
	case "process_exit":
		return CategoryProcess, "exit"
	case "file_access":
		return CategoryFile, stringValue(eventMap["file_action"])
	case "network_connect":
		return CategoryNetwork, "connect"
	case "network_accept":
		return CategoryNetwork, "accept"
	case "privilege_change":
		return CategoryIdentity, "credential_change"
	}
	return "", ""
}

func visibilityForEvent(eventMap map[string]any) string {
	if value, ok := eventMap["args_truncated"].(bool); ok && value {
		return "partial"
	}
	return "complete"
}

func priorityForEvent(event BehaviorEvent) EventPriority {
	if event.Category == CategoryIsolation || event.Operation == "exit" ||
		event.Operation == "create" || event.Operation == "delete" ||
		event.Operation == "rename" || event.Operation == "chmod" ||
		event.Operation == "credential_change" {
		return PriorityStateChange
	}
	if isAggregatable(event) {
		return PriorityRepetitiveIO
	}
	return PriorityProcessNetwork
}

func stringValue(value any) string {
	switch typed := value.(type) {
	case string:
		return typed
	case fmt.Stringer:
		return typed.String()
	default:
		return ""
	}
}

func numberValue(value any) int64 {
	switch typed := value.(type) {
	case int:
		return int64(typed)
	case int32:
		return int64(typed)
	case int64:
		return typed
	case uint32:
		return int64(typed)
	case uint64:
		return int64(typed)
	case float64:
		return int64(typed)
	default:
		return 0
	}
}

func errorCode(err error) string {
	if err == nil {
		return ""
	}
	value := err.Error()
	if index := strings.IndexByte(value, ':'); index >= 0 {
		value = value[:index]
	}
	value = strings.ToLower(strings.TrimSpace(value))
	value = strings.ReplaceAll(value, " ", "_")
	if len(value) > 96 {
		value = value[:96]
	}
	return value
}
