// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.24.4
// source: proto/builder_comm.proto

package builderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BuilderService_GetBuilderInfo_FullMethodName        = "/builder_comm.v1.BuilderService/GetBuilderInfo"
	BuilderService_StartBuild_FullMethodName            = "/builder_comm.v1.BuilderService/StartBuild"
	BuilderService_GetPackageBuildStatus_FullMethodName = "/builder_comm.v1.BuilderService/GetPackageBuildStatus"
	BuilderService_ReviewBuild_FullMethodName           = "/builder_comm.v1.BuilderService/ReviewBuild"
	BuilderService_SignPackage_FullMethodName           = "/builder_comm.v1.BuilderService/SignPackage"
)

// BuilderServiceClient is the client API for BuilderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BuilderService - eBPF Detection Package Builder
type BuilderServiceClient interface {
	GetBuilderInfo(ctx context.Context, in *GetBuilderInfoRequest, opts ...grpc.CallOption) (*GetBuilderInfoResponse, error)
	// NOTE: 设计文档中命名为 StartPackageBuild，保持当前命名以兼容现有客户端
	StartBuild(ctx context.Context, in *StartBuildRequest, opts ...grpc.CallOption) (*StartBuildResponse, error)
	GetPackageBuildStatus(ctx context.Context, in *GetPackageBuildStatusRequest, opts ...grpc.CallOption) (*GetPackageBuildStatusResponse, error)
	ReviewBuild(ctx context.Context, in *ReviewBuildRequest, opts ...grpc.CallOption) (*ReviewBuildResponse, error)
	SignPackage(ctx context.Context, in *SignPackageRequest, opts ...grpc.CallOption) (*SignPackageResponse, error)
}

type builderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuilderServiceClient(cc grpc.ClientConnInterface) BuilderServiceClient {
	return &builderServiceClient{cc}
}

func (c *builderServiceClient) GetBuilderInfo(ctx context.Context, in *GetBuilderInfoRequest, opts ...grpc.CallOption) (*GetBuilderInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBuilderInfoResponse)
	err := c.cc.Invoke(ctx, BuilderService_GetBuilderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderServiceClient) StartBuild(ctx context.Context, in *StartBuildRequest, opts ...grpc.CallOption) (*StartBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBuildResponse)
	err := c.cc.Invoke(ctx, BuilderService_StartBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderServiceClient) GetPackageBuildStatus(ctx context.Context, in *GetPackageBuildStatusRequest, opts ...grpc.CallOption) (*GetPackageBuildStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPackageBuildStatusResponse)
	err := c.cc.Invoke(ctx, BuilderService_GetPackageBuildStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderServiceClient) ReviewBuild(ctx context.Context, in *ReviewBuildRequest, opts ...grpc.CallOption) (*ReviewBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewBuildResponse)
	err := c.cc.Invoke(ctx, BuilderService_ReviewBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderServiceClient) SignPackage(ctx context.Context, in *SignPackageRequest, opts ...grpc.CallOption) (*SignPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignPackageResponse)
	err := c.cc.Invoke(ctx, BuilderService_SignPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuilderServiceServer is the server API for BuilderService service.
// All implementations must embed UnimplementedBuilderServiceServer
// for forward compatibility.
//
// BuilderService - eBPF Detection Package Builder
type BuilderServiceServer interface {
	GetBuilderInfo(context.Context, *GetBuilderInfoRequest) (*GetBuilderInfoResponse, error)
	// NOTE: 设计文档中命名为 StartPackageBuild，保持当前命名以兼容现有客户端
	StartBuild(context.Context, *StartBuildRequest) (*StartBuildResponse, error)
	GetPackageBuildStatus(context.Context, *GetPackageBuildStatusRequest) (*GetPackageBuildStatusResponse, error)
	ReviewBuild(context.Context, *ReviewBuildRequest) (*ReviewBuildResponse, error)
	SignPackage(context.Context, *SignPackageRequest) (*SignPackageResponse, error)
	mustEmbedUnimplementedBuilderServiceServer()
}

// UnimplementedBuilderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuilderServiceServer struct{}

func (UnimplementedBuilderServiceServer) GetBuilderInfo(context.Context, *GetBuilderInfoRequest) (*GetBuilderInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBuilderInfo not implemented")
}
func (UnimplementedBuilderServiceServer) StartBuild(context.Context, *StartBuildRequest) (*StartBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBuild not implemented")
}
func (UnimplementedBuilderServiceServer) GetPackageBuildStatus(context.Context, *GetPackageBuildStatusRequest) (*GetPackageBuildStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPackageBuildStatus not implemented")
}
func (UnimplementedBuilderServiceServer) ReviewBuild(context.Context, *ReviewBuildRequest) (*ReviewBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewBuild not implemented")
}
func (UnimplementedBuilderServiceServer) SignPackage(context.Context, *SignPackageRequest) (*SignPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignPackage not implemented")
}
func (UnimplementedBuilderServiceServer) mustEmbedUnimplementedBuilderServiceServer() {}
func (UnimplementedBuilderServiceServer) testEmbeddedByValue()                        {}

// UnsafeBuilderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuilderServiceServer will
// result in compilation errors.
type UnsafeBuilderServiceServer interface {
	mustEmbedUnimplementedBuilderServiceServer()
}

func RegisterBuilderServiceServer(s grpc.ServiceRegistrar, srv BuilderServiceServer) {
	// If the following call panics, it indicates UnimplementedBuilderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuilderService_ServiceDesc, srv)
}

func _BuilderService_GetBuilderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuilderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).GetBuilderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_GetBuilderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).GetBuilderInfo(ctx, req.(*GetBuilderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuilderService_StartBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).StartBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_StartBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).StartBuild(ctx, req.(*StartBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuilderService_GetPackageBuildStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackageBuildStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).GetPackageBuildStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_GetPackageBuildStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).GetPackageBuildStatus(ctx, req.(*GetPackageBuildStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuilderService_ReviewBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).ReviewBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_ReviewBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).ReviewBuild(ctx, req.(*ReviewBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuilderService_SignPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).SignPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_SignPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).SignPackage(ctx, req.(*SignPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuilderService_ServiceDesc is the grpc.ServiceDesc for BuilderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuilderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "builder_comm.v1.BuilderService",
	HandlerType: (*BuilderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBuilderInfo",
			Handler:    _BuilderService_GetBuilderInfo_Handler,
		},
		{
			MethodName: "StartBuild",
			Handler:    _BuilderService_StartBuild_Handler,
		},
		{
			MethodName: "GetPackageBuildStatus",
			Handler:    _BuilderService_GetPackageBuildStatus_Handler,
		},
		{
			MethodName: "ReviewBuild",
			Handler:    _BuilderService_ReviewBuild_Handler,
		},
		{
			MethodName: "SignPackage",
			Handler:    _BuilderService_SignPackage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/builder_comm.proto",
}
