// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent_session_comm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentSessionSourceUsage struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	InputTokens              *int64                 `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3,oneof" json:"input_tokens,omitempty"`
	OutputTokens             *int64                 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3,oneof" json:"output_tokens,omitempty"`
	CacheCreationInputTokens *int64                 `protobuf:"varint,3,opt,name=cache_creation_input_tokens,json=cacheCreationInputTokens,proto3,oneof" json:"cache_creation_input_tokens,omitempty"`
	CacheReadInputTokens     *int64                 `protobuf:"varint,4,opt,name=cache_read_input_tokens,json=cacheReadInputTokens,proto3,oneof" json:"cache_read_input_tokens,omitempty"`
	Coverage                 string                 `protobuf:"bytes,5,opt,name=coverage,proto3" json:"coverage,omitempty"` // none|partial|complete
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AgentSessionSourceUsage) Reset() {
	*x = AgentSessionSourceUsage{}
	mi := &file_agent_session_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionSourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionSourceUsage) ProtoMessage() {}

func (x *AgentSessionSourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_session_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionSourceUsage.ProtoReflect.Descriptor instead.
func (*AgentSessionSourceUsage) Descriptor() ([]byte, []int) {
	return file_agent_session_comm_proto_rawDescGZIP(), []int{0}
}

func (x *AgentSessionSourceUsage) GetInputTokens() int64 {
	if x != nil && x.InputTokens != nil {
		return *x.InputTokens
	}
	return 0
}

func (x *AgentSessionSourceUsage) GetOutputTokens() int64 {
	if x != nil && x.OutputTokens != nil {
		return *x.OutputTokens
	}
	return 0
}

func (x *AgentSessionSourceUsage) GetCacheCreationInputTokens() int64 {
	if x != nil && x.CacheCreationInputTokens != nil {
		return *x.CacheCreationInputTokens
	}
	return 0
}

func (x *AgentSessionSourceUsage) GetCacheReadInputTokens() int64 {
	if x != nil && x.CacheReadInputTokens != nil {
		return *x.CacheReadInputTokens
	}
	return 0
}

func (x *AgentSessionSourceUsage) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

type AgentSessionItem struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	ItemId             string                   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	SourceMessageId    string                   `protobuf:"bytes,2,opt,name=source_message_id,json=sourceMessageId,proto3" json:"source_message_id,omitempty"`
	SourcePartId       string                   `protobuf:"bytes,3,opt,name=source_part_id,json=sourcePartId,proto3" json:"source_part_id,omitempty"`
	SourceRevision     string                   `protobuf:"bytes,4,opt,name=source_revision,json=sourceRevision,proto3" json:"source_revision,omitempty"`
	SourceSequence     uint64                   `protobuf:"varint,5,opt,name=source_sequence,json=sourceSequence,proto3" json:"source_sequence,omitempty"`
	TurnId             string                   `protobuf:"bytes,6,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	ParentItemId       string                   `protobuf:"bytes,7,opt,name=parent_item_id,json=parentItemId,proto3" json:"parent_item_id,omitempty"`
	ItemType           string                   `protobuf:"bytes,8,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Role               string                   `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`
	OccurredAtUnixNano int64                    `protobuf:"varint,10,opt,name=occurred_at_unix_nano,json=occurredAtUnixNano,proto3" json:"occurred_at_unix_nano,omitempty"`
	NormalizedJson     []byte                   `protobuf:"bytes,11,opt,name=normalized_json,json=normalizedJson,proto3" json:"normalized_json,omitempty"`
	ContentDigest      string                   `protobuf:"bytes,12,opt,name=content_digest,json=contentDigest,proto3" json:"content_digest,omitempty"`
	SourceDigest       string                   `protobuf:"bytes,13,opt,name=source_digest,json=sourceDigest,proto3" json:"source_digest,omitempty"`
	PreviousItemDigest string                   `protobuf:"bytes,14,opt,name=previous_item_digest,json=previousItemDigest,proto3" json:"previous_item_digest,omitempty"`
	SourceUsage        *AgentSessionSourceUsage `protobuf:"bytes,15,opt,name=source_usage,json=sourceUsage,proto3" json:"source_usage,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentSessionItem) Reset() {
	*x = AgentSessionItem{}
	mi := &file_agent_session_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionItem) ProtoMessage() {}

func (x *AgentSessionItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_session_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionItem.ProtoReflect.Descriptor instead.
func (*AgentSessionItem) Descriptor() ([]byte, []int) {
	return file_agent_session_comm_proto_rawDescGZIP(), []int{1}
}

func (x *AgentSessionItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AgentSessionItem) GetSourceMessageId() string {
	if x != nil {
		return x.SourceMessageId
	}
	return ""
}

func (x *AgentSessionItem) GetSourcePartId() string {
	if x != nil {
		return x.SourcePartId
	}
	return ""
}

func (x *AgentSessionItem) GetSourceRevision() string {
	if x != nil {
		return x.SourceRevision
	}
	return ""
}

func (x *AgentSessionItem) GetSourceSequence() uint64 {
	if x != nil {
		return x.SourceSequence
	}
	return 0
}

func (x *AgentSessionItem) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *AgentSessionItem) GetParentItemId() string {
	if x != nil {
		return x.ParentItemId
	}
	return ""
}

func (x *AgentSessionItem) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *AgentSessionItem) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentSessionItem) GetOccurredAtUnixNano() int64 {
	if x != nil {
		return x.OccurredAtUnixNano
	}
	return 0
}

func (x *AgentSessionItem) GetNormalizedJson() []byte {
	if x != nil {
		return x.NormalizedJson
	}
	return nil
}

func (x *AgentSessionItem) GetContentDigest() string {
	if x != nil {
		return x.ContentDigest
	}
	return ""
}

func (x *AgentSessionItem) GetSourceDigest() string {
	if x != nil {
		return x.SourceDigest
	}
	return ""
}

func (x *AgentSessionItem) GetPreviousItemDigest() string {
	if x != nil {
		return x.PreviousItemDigest
	}
	return ""
}

func (x *AgentSessionItem) GetSourceUsage() *AgentSessionSourceUsage {
	if x != nil {
		return x.SourceUsage
	}
	return nil
}

type AgentSessionBatchRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Schema                     string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // aegis.agent_session_batch.v1
	BatchId                    string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	HostId                     string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	AgentType                  string                 `protobuf:"bytes,4,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // claude-code|codex
	SourceSubjectUid           int64                  `protobuf:"varint,5,opt,name=source_subject_uid,json=sourceSubjectUid,proto3" json:"source_subject_uid,omitempty"`
	SourceStorageNamespaceHash string                 `protobuf:"bytes,6,opt,name=source_storage_namespace_hash,json=sourceStorageNamespaceHash,proto3" json:"source_storage_namespace_hash,omitempty"`
	SourceSessionId            string                 `protobuf:"bytes,7,opt,name=source_session_id,json=sourceSessionId,proto3" json:"source_session_id,omitempty"`
	SourceVersion              string                 `protobuf:"bytes,8,opt,name=source_version,json=sourceVersion,proto3" json:"source_version,omitempty"`
	SourceMode                 string                 `protobuf:"bytes,9,opt,name=source_mode,json=sourceMode,proto3" json:"source_mode,omitempty"`                       // static_scan|static_backfill
	SourceAttestation          string                 `protobuf:"bytes,10,opt,name=source_attestation,json=sourceAttestation,proto3" json:"source_attestation,omitempty"` // versioned_static_parser
	FirstSequence              uint64                 `protobuf:"varint,11,opt,name=first_sequence,json=firstSequence,proto3" json:"first_sequence,omitempty"`
	LastSequence               uint64                 `protobuf:"varint,12,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"`
	Items                      []*AgentSessionItem    `protobuf:"bytes,13,rep,name=items,proto3" json:"items,omitempty"`
	Compression                string                 `protobuf:"bytes,14,opt,name=compression,proto3" json:"compression,omitempty"`
	BatchDigest                string                 `protobuf:"bytes,15,opt,name=batch_digest,json=batchDigest,proto3" json:"batch_digest,omitempty"`
	CollectionCoverage         string                 `protobuf:"bytes,16,opt,name=collection_coverage,json=collectionCoverage,proto3" json:"collection_coverage,omitempty"`
	SessionMetadataJson        []byte                 `protobuf:"bytes,17,opt,name=session_metadata_json,json=sessionMetadataJson,proto3" json:"session_metadata_json,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AgentSessionBatchRequest) Reset() {
	*x = AgentSessionBatchRequest{}
	mi := &file_agent_session_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionBatchRequest) ProtoMessage() {}

func (x *AgentSessionBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_session_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionBatchRequest.ProtoReflect.Descriptor instead.
func (*AgentSessionBatchRequest) Descriptor() ([]byte, []int) {
	return file_agent_session_comm_proto_rawDescGZIP(), []int{2}
}

func (x *AgentSessionBatchRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetSourceSubjectUid() int64 {
	if x != nil {
		return x.SourceSubjectUid
	}
	return 0
}

func (x *AgentSessionBatchRequest) GetSourceStorageNamespaceHash() string {
	if x != nil {
		return x.SourceStorageNamespaceHash
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetSourceSessionId() string {
	if x != nil {
		return x.SourceSessionId
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetSourceVersion() string {
	if x != nil {
		return x.SourceVersion
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetSourceMode() string {
	if x != nil {
		return x.SourceMode
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetSourceAttestation() string {
	if x != nil {
		return x.SourceAttestation
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetFirstSequence() uint64 {
	if x != nil {
		return x.FirstSequence
	}
	return 0
}

func (x *AgentSessionBatchRequest) GetLastSequence() uint64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

func (x *AgentSessionBatchRequest) GetItems() []*AgentSessionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AgentSessionBatchRequest) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetBatchDigest() string {
	if x != nil {
		return x.BatchDigest
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetCollectionCoverage() string {
	if x != nil {
		return x.CollectionCoverage
	}
	return ""
}

func (x *AgentSessionBatchRequest) GetSessionMetadataJson() []byte {
	if x != nil {
		return x.SessionMetadataJson
	}
	return nil
}

type AgentSessionBatchResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Success                 bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AcceptedThroughSequence uint64                 `protobuf:"varint,2,opt,name=accepted_through_sequence,json=acceptedThroughSequence,proto3" json:"accepted_through_sequence,omitempty"`
	ErrorCode               string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message                 string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Retryable               bool                   `protobuf:"varint,5,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AgentSessionBatchResponse) Reset() {
	*x = AgentSessionBatchResponse{}
	mi := &file_agent_session_comm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionBatchResponse) ProtoMessage() {}

func (x *AgentSessionBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_session_comm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionBatchResponse.ProtoReflect.Descriptor instead.
func (*AgentSessionBatchResponse) Descriptor() ([]byte, []int) {
	return file_agent_session_comm_proto_rawDescGZIP(), []int{3}
}

func (x *AgentSessionBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentSessionBatchResponse) GetAcceptedThroughSequence() uint64 {
	if x != nil {
		return x.AcceptedThroughSequence
	}
	return 0
}

func (x *AgentSessionBatchResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AgentSessionBatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentSessionBatchResponse) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_agent_session_comm_proto protoreflect.FileDescriptor

const file_agent_session_comm_proto_rawDesc = "" +
	"\n" +
	"\x18agent_session_comm.proto\x12\x15agent_session_comm.v1\"\xe6\x02\n" +
	"\x17AgentSessionSourceUsage\x12&\n" +
	"\finput_tokens\x18\x01 \x01(\x03H\x00R\vinputTokens\x88\x01\x01\x12(\n" +
	"\routput_tokens\x18\x02 \x01(\x03H\x01R\foutputTokens\x88\x01\x01\x12B\n" +
	"\x1bcache_creation_input_tokens\x18\x03 \x01(\x03H\x02R\x18cacheCreationInputTokens\x88\x01\x01\x12:\n" +
	"\x17cache_read_input_tokens\x18\x04 \x01(\x03H\x03R\x14cacheReadInputTokens\x88\x01\x01\x12\x1a\n" +
	"\bcoverage\x18\x05 \x01(\tR\bcoverageB\x0f\n" +
	"\r_input_tokensB\x10\n" +
	"\x0e_output_tokensB\x1e\n" +
	"\x1c_cache_creation_input_tokensB\x1a\n" +
	"\x18_cache_read_input_tokens\"\xec\x04\n" +
	"\x10AgentSessionItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12*\n" +
	"\x11source_message_id\x18\x02 \x01(\tR\x0fsourceMessageId\x12$\n" +
	"\x0esource_part_id\x18\x03 \x01(\tR\fsourcePartId\x12'\n" +
	"\x0fsource_revision\x18\x04 \x01(\tR\x0esourceRevision\x12'\n" +
	"\x0fsource_sequence\x18\x05 \x01(\x04R\x0esourceSequence\x12\x17\n" +
	"\aturn_id\x18\x06 \x01(\tR\x06turnId\x12$\n" +
	"\x0eparent_item_id\x18\a \x01(\tR\fparentItemId\x12\x1b\n" +
	"\titem_type\x18\b \x01(\tR\bitemType\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\x121\n" +
	"\x15occurred_at_unix_nano\x18\n" +
	" \x01(\x03R\x12occurredAtUnixNano\x12'\n" +
	"\x0fnormalized_json\x18\v \x01(\fR\x0enormalizedJson\x12%\n" +
	"\x0econtent_digest\x18\f \x01(\tR\rcontentDigest\x12#\n" +
	"\rsource_digest\x18\r \x01(\tR\fsourceDigest\x120\n" +
	"\x14previous_item_digest\x18\x0e \x01(\tR\x12previousItemDigest\x12Q\n" +
	"\fsource_usage\x18\x0f \x01(\v2..agent_session_comm.v1.AgentSessionSourceUsageR\vsourceUsage\"\xce\x05\n" +
	"\x18AgentSessionBatchRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x04 \x01(\tR\tagentType\x12,\n" +
	"\x12source_subject_uid\x18\x05 \x01(\x03R\x10sourceSubjectUid\x12A\n" +
	"\x1dsource_storage_namespace_hash\x18\x06 \x01(\tR\x1asourceStorageNamespaceHash\x12*\n" +
	"\x11source_session_id\x18\a \x01(\tR\x0fsourceSessionId\x12%\n" +
	"\x0esource_version\x18\b \x01(\tR\rsourceVersion\x12\x1f\n" +
	"\vsource_mode\x18\t \x01(\tR\n" +
	"sourceMode\x12-\n" +
	"\x12source_attestation\x18\n" +
	" \x01(\tR\x11sourceAttestation\x12%\n" +
	"\x0efirst_sequence\x18\v \x01(\x04R\rfirstSequence\x12#\n" +
	"\rlast_sequence\x18\f \x01(\x04R\flastSequence\x12=\n" +
	"\x05items\x18\r \x03(\v2'.agent_session_comm.v1.AgentSessionItemR\x05items\x12 \n" +
	"\vcompression\x18\x0e \x01(\tR\vcompression\x12!\n" +
	"\fbatch_digest\x18\x0f \x01(\tR\vbatchDigest\x12/\n" +
	"\x13collection_coverage\x18\x10 \x01(\tR\x12collectionCoverage\x122\n" +
	"\x15session_metadata_json\x18\x11 \x01(\fR\x13sessionMetadataJson\"\xc8\x01\n" +
	"\x19AgentSessionBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12:\n" +
	"\x19accepted_through_sequence\x18\x02 \x01(\x04R\x17acceptedThroughSequence\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x05 \x01(\bR\tretryable2\x93\x01\n" +
	"\x13AgentSessionService\x12|\n" +
	"\x17ReportAgentSessionBatch\x12/.agent_session_comm.v1.AgentSessionBatchRequest\x1a0.agent_session_comm.v1.AgentSessionBatchResponseB\x16Z\x14server/pkg/api/v1;pbb\x06proto3"

var (
	file_agent_session_comm_proto_rawDescOnce sync.Once
	file_agent_session_comm_proto_rawDescData []byte
)

func file_agent_session_comm_proto_rawDescGZIP() []byte {
	file_agent_session_comm_proto_rawDescOnce.Do(func() {
		file_agent_session_comm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_session_comm_proto_rawDesc), len(file_agent_session_comm_proto_rawDesc)))
	})
	return file_agent_session_comm_proto_rawDescData
}

var file_agent_session_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agent_session_comm_proto_goTypes = []any{
	(*AgentSessionSourceUsage)(nil),   // 0: agent_session_comm.v1.AgentSessionSourceUsage
	(*AgentSessionItem)(nil),          // 1: agent_session_comm.v1.AgentSessionItem
	(*AgentSessionBatchRequest)(nil),  // 2: agent_session_comm.v1.AgentSessionBatchRequest
	(*AgentSessionBatchResponse)(nil), // 3: agent_session_comm.v1.AgentSessionBatchResponse
}
var file_agent_session_comm_proto_depIdxs = []int32{
	0, // 0: agent_session_comm.v1.AgentSessionItem.source_usage:type_name -> agent_session_comm.v1.AgentSessionSourceUsage
	1, // 1: agent_session_comm.v1.AgentSessionBatchRequest.items:type_name -> agent_session_comm.v1.AgentSessionItem
	2, // 2: agent_session_comm.v1.AgentSessionService.ReportAgentSessionBatch:input_type -> agent_session_comm.v1.AgentSessionBatchRequest
	3, // 3: agent_session_comm.v1.AgentSessionService.ReportAgentSessionBatch:output_type -> agent_session_comm.v1.AgentSessionBatchResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agent_session_comm_proto_init() }
func file_agent_session_comm_proto_init() {
	if File_agent_session_comm_proto != nil {
		return
	}
	file_agent_session_comm_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_session_comm_proto_rawDesc), len(file_agent_session_comm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_session_comm_proto_goTypes,
		DependencyIndexes: file_agent_session_comm_proto_depIdxs,
		MessageInfos:      file_agent_session_comm_proto_msgTypes,
	}.Build()
	File_agent_session_comm_proto = out.File
	file_agent_session_comm_proto_goTypes = nil
	file_agent_session_comm_proto_depIdxs = nil
}
