// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: agent_session_comm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentSessionService_ReportAgentSessionBatch_FullMethodName = "/agent_session_comm.v1.AgentSessionService/ReportAgentSessionBatch"
)

// AgentSessionServiceClient is the client API for AgentSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentSessionServiceClient interface {
	ReportAgentSessionBatch(ctx context.Context, in *AgentSessionBatchRequest, opts ...grpc.CallOption) (*AgentSessionBatchResponse, error)
}

type agentSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentSessionServiceClient(cc grpc.ClientConnInterface) AgentSessionServiceClient {
	return &agentSessionServiceClient{cc}
}

func (c *agentSessionServiceClient) ReportAgentSessionBatch(ctx context.Context, in *AgentSessionBatchRequest, opts ...grpc.CallOption) (*AgentSessionBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentSessionBatchResponse)
	err := c.cc.Invoke(ctx, AgentSessionService_ReportAgentSessionBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentSessionServiceServer is the server API for AgentSessionService service.
// All implementations must embed UnimplementedAgentSessionServiceServer
// for forward compatibility.
type AgentSessionServiceServer interface {
	ReportAgentSessionBatch(context.Context, *AgentSessionBatchRequest) (*AgentSessionBatchResponse, error)
	mustEmbedUnimplementedAgentSessionServiceServer()
}

// UnimplementedAgentSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentSessionServiceServer struct{}

func (UnimplementedAgentSessionServiceServer) ReportAgentSessionBatch(context.Context, *AgentSessionBatchRequest) (*AgentSessionBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportAgentSessionBatch not implemented")
}
func (UnimplementedAgentSessionServiceServer) mustEmbedUnimplementedAgentSessionServiceServer() {}
func (UnimplementedAgentSessionServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentSessionServiceServer will
// result in compilation errors.
type UnsafeAgentSessionServiceServer interface {
	mustEmbedUnimplementedAgentSessionServiceServer()
}

func RegisterAgentSessionServiceServer(s grpc.ServiceRegistrar, srv AgentSessionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentSessionService_ServiceDesc, srv)
}

func _AgentSessionService_ReportAgentSessionBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentSessionBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSessionServiceServer).ReportAgentSessionBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSessionService_ReportAgentSessionBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSessionServiceServer).ReportAgentSessionBatch(ctx, req.(*AgentSessionBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentSessionService_ServiceDesc is the grpc.ServiceDesc for AgentSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent_session_comm.v1.AgentSessionService",
	HandlerType: (*AgentSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportAgentSessionBatch",
			Handler:    _AgentSessionService_ReportAgentSessionBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_session_comm.proto",
}
