// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: api_server_comm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                          // 任务ID
	HostId         string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                          // 目标主机ID
	RuleId         string                 `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`                          // 规则ID（可选）
	ScriptContent  string                 `protobuf:"bytes,4,opt,name=script_content,json=scriptContent,proto3" json:"script_content,omitempty"`     // 脚本内容
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 超时时间（秒）
	TaskType       string                 `protobuf:"bytes,6,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`                    // 任务类型: CHECK, FIX, VULNERABILITY_FIX, POC_VERIFY
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForwardCommandRequest) Reset() {
	*x = ForwardCommandRequest{}
	mi := &file_api_server_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardCommandRequest) ProtoMessage() {}

func (x *ForwardCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardCommandRequest.ProtoReflect.Descriptor instead.
func (*ForwardCommandRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardCommandRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ForwardCommandRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ForwardCommandRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *ForwardCommandRequest) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

func (x *ForwardCommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ForwardCommandRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type ForwardCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardCommandResponse) Reset() {
	*x = ForwardCommandResponse{}
	mi := &file_api_server_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardCommandResponse) ProtoMessage() {}

func (x *ForwardCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardCommandResponse.ProtoReflect.Descriptor instead.
func (*ForwardCommandResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardCommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ForwardCommandResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ToolExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CallId         string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	HostId         string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                          // 目标主机ID
	Tool           string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`                                            // 工具名称
	Arguments      string                 `protobuf:"bytes,4,opt,name=arguments,proto3" json:"arguments,omitempty"`                                  // JSON格式参数
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 超时时间（秒）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolExecuteRequest) Reset() {
	*x = ToolExecuteRequest{}
	mi := &file_api_server_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecuteRequest) ProtoMessage() {}

func (x *ToolExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecuteRequest.ProtoReflect.Descriptor instead.
func (*ToolExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{2}
}

func (x *ToolExecuteRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolExecuteRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ToolExecuteRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolExecuteRequest) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *ToolExecuteRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ToolExecuteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallId          string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Result          string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // JSON格式结果
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"` // 执行时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolExecuteResponse) Reset() {
	*x = ToolExecuteResponse{}
	mi := &file_api_server_comm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecuteResponse) ProtoMessage() {}

func (x *ToolExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecuteResponse.ProtoReflect.Descriptor instead.
func (*ToolExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{3}
}

func (x *ToolExecuteResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolExecuteResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolExecuteResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type GetAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // 主机ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	mi := &file_api_server_comm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentStatusRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type GetAgentStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Connected       bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"` // 是否连接
	HostId          string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname        string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress       string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	OsType          string                 `protobuf:"bytes,5,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	LastHeartbeat   int64                  `protobuf:"varint,7,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`       // Unix timestamp
	PendingCommands int32                  `protobuf:"varint,8,opt,name=pending_commands,json=pendingCommands,proto3" json:"pending_commands,omitempty"` // 待处理命令数
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAgentStatusResponse) Reset() {
	*x = GetAgentStatusResponse{}
	mi := &file_api_server_comm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusResponse) ProtoMessage() {}

func (x *GetAgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentStatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *GetAgentStatusResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *GetAgentStatusResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetAgentStatusResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *GetAgentStatusResponse) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *GetAgentStatusResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *GetAgentStatusResponse) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *GetAgentStatusResponse) GetPendingCommands() int32 {
	if x != nil {
		return x.PendingCommands
	}
	return 0
}

type ListConnectedAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                    // 页码（从1开始）
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`            // 每页大小
	StatusFilter  string                 `protobuf:"bytes,3,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // 状态过滤: all, online, offline
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectedAgentsRequest) Reset() {
	*x = ListConnectedAgentsRequest{}
	mi := &file_api_server_comm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectedAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectedAgentsRequest) ProtoMessage() {}

func (x *ListConnectedAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectedAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectedAgentsRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{6}
}

func (x *ListConnectedAgentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConnectedAgentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConnectedAgentsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListConnectedAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	OnlineCount   int32                  `protobuf:"varint,3,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	OfflineCount  int32                  `protobuf:"varint,4,opt,name=offline_count,json=offlineCount,proto3" json:"offline_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectedAgentsResponse) Reset() {
	*x = ListConnectedAgentsResponse{}
	mi := &file_api_server_comm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectedAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectedAgentsResponse) ProtoMessage() {}

func (x *ListConnectedAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectedAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectedAgentsResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{7}
}

func (x *ListConnectedAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListConnectedAgentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListConnectedAgentsResponse) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *ListConnectedAgentsResponse) GetOfflineCount() int32 {
	if x != nil {
		return x.OfflineCount
	}
	return 0
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	OsType        string                 `protobuf:"bytes,4,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsVersion     string                 `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Arch          string                 `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`
	Connected     bool                   `protobuf:"varint,8,opt,name=connected,proto3" json:"connected,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,9,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	RegisteredAt  int64                  `protobuf:"varint,10,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_api_server_comm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{8}
}

func (x *AgentInfo) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AgentInfo) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *AgentInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *AgentInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentInfo) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *AgentInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *AgentInfo) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // 服务名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_server_comm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // running, degraded, unhealthy
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_server_comm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type UpdateAgentRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // 目标主机ID（空表示所有Agent）
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`               // full_sync, incremental
	Rules         []*AgentRuleUpdate     `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentRulesRequest) Reset() {
	*x = UpdateAgentRulesRequest{}
	mi := &file_api_server_comm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRulesRequest) ProtoMessage() {}

func (x *UpdateAgentRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRulesRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRulesRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateAgentRulesRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *UpdateAgentRulesRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpdateAgentRulesRequest) GetRules() []*AgentRuleUpdate {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AgentRuleUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`   // add, update, delete
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // YAML格式Sigma规则
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRuleUpdate) Reset() {
	*x = AgentRuleUpdate{}
	mi := &file_api_server_comm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRuleUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRuleUpdate) ProtoMessage() {}

func (x *AgentRuleUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRuleUpdate.ProtoReflect.Descriptor instead.
func (*AgentRuleUpdate) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{12}
}

func (x *AgentRuleUpdate) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *AgentRuleUpdate) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AgentRuleUpdate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateAgentRulesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AffectedAgents int32                  `protobuf:"varint,2,opt,name=affected_agents,json=affectedAgents,proto3" json:"affected_agents,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAgentRulesResponse) Reset() {
	*x = UpdateAgentRulesResponse{}
	mi := &file_api_server_comm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRulesResponse) ProtoMessage() {}

func (x *UpdateAgentRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRulesResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgentRulesResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAgentRulesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateAgentRulesResponse) GetAffectedAgents() int32 {
	if x != nil {
		return x.AffectedAgents
	}
	return 0
}

func (x *UpdateAgentRulesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExecuteBlockCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // 命令ID
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`          // 目标主机ID
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                        // kill_process, block_network, etc.
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`                        // 目标（PID、IP等）
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                        // 阻断原因
	AlertId       string                 `protobuf:"bytes,6,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`       // 关联告警ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBlockCommandRequest) Reset() {
	*x = ExecuteBlockCommandRequest{}
	mi := &file_api_server_comm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBlockCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBlockCommandRequest) ProtoMessage() {}

func (x *ExecuteBlockCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBlockCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBlockCommandRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteBlockCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteBlockCommandRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ExecuteBlockCommandRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteBlockCommandRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ExecuteBlockCommandRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ExecuteBlockCommandRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

type ExecuteBlockCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ExecutedAt    int64                  `protobuf:"varint,4,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"` // 执行时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBlockCommandResponse) Reset() {
	*x = ExecuteBlockCommandResponse{}
	mi := &file_api_server_comm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBlockCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBlockCommandResponse) ProtoMessage() {}

func (x *ExecuteBlockCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBlockCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBlockCommandResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteBlockCommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteBlockCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteBlockCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteBlockCommandResponse) GetExecutedAt() int64 {
	if x != nil {
		return x.ExecutedAt
	}
	return 0
}

type CollectSoftwareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // 主机ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectSoftwareRequest) Reset() {
	*x = CollectSoftwareRequest{}
	mi := &file_api_server_comm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectSoftwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectSoftwareRequest) ProtoMessage() {}

func (x *CollectSoftwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectSoftwareRequest.ProtoReflect.Descriptor instead.
func (*CollectSoftwareRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{16}
}

func (x *CollectSoftwareRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type CollectSoftwareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SoftwareJson  string                 `protobuf:"bytes,2,opt,name=software_json,json=softwareJson,proto3" json:"software_json,omitempty"` // JSON格式的软件列表
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectSoftwareResponse) Reset() {
	*x = CollectSoftwareResponse{}
	mi := &file_api_server_comm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectSoftwareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectSoftwareResponse) ProtoMessage() {}

func (x *CollectSoftwareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectSoftwareResponse.ProtoReflect.Descriptor instead.
func (*CollectSoftwareResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{17}
}

func (x *CollectSoftwareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CollectSoftwareResponse) GetSoftwareJson() string {
	if x != nil {
		return x.SoftwareJson
	}
	return ""
}

func (x *CollectSoftwareResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CommandResultNotification 命令执行结果通知
type CommandResultNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	IsFinal       bool                   `protobuf:"varint,6,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResultNotification) Reset() {
	*x = CommandResultNotification{}
	mi := &file_api_server_comm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResultNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResultNotification) ProtoMessage() {}

func (x *CommandResultNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResultNotification.ProtoReflect.Descriptor instead.
func (*CommandResultNotification) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{18}
}

func (x *CommandResultNotification) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CommandResultNotification) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CommandResultNotification) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResultNotification) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResultNotification) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResultNotification) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *CommandResultNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// AgentStatusChangeNotification Agent状态变更通知
type AgentStatusChangeNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostId         string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PreviousStatus string                 `protobuf:"bytes,3,opt,name=previous_status,json=previousStatus,proto3" json:"previous_status,omitempty"` // online, offline
	CurrentStatus  string                 `protobuf:"bytes,4,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentStatusChangeNotification) Reset() {
	*x = AgentStatusChangeNotification{}
	mi := &file_api_server_comm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusChangeNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusChangeNotification) ProtoMessage() {}

func (x *AgentStatusChangeNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusChangeNotification.ProtoReflect.Descriptor instead.
func (*AgentStatusChangeNotification) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{19}
}

func (x *AgentStatusChangeNotification) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AgentStatusChangeNotification) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentStatusChangeNotification) GetPreviousStatus() string {
	if x != nil {
		return x.PreviousStatus
	}
	return ""
}

func (x *AgentStatusChangeNotification) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

func (x *AgentStatusChangeNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DetectionPackageCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // install, uninstall, disable
	PackageId     string                 `protobuf:"bytes,3,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	PackageUrl    string                 `protobuf:"bytes,5,opt,name=package_url,json=packageUrl,proto3" json:"package_url,omitempty"`
	SignatureUrl  string                 `protobuf:"bytes,6,opt,name=signature_url,json=signatureUrl,proto3" json:"signature_url,omitempty"`
	PackageSize   int64                  `protobuf:"varint,7,opt,name=package_size,json=packageSize,proto3" json:"package_size,omitempty"`
	Rollback      bool                   `protobuf:"varint,8,opt,name=rollback,proto3" json:"rollback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionPackageCommandRequest) Reset() {
	*x = DetectionPackageCommandRequest{}
	mi := &file_api_server_comm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionPackageCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionPackageCommandRequest) ProtoMessage() {}

func (x *DetectionPackageCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionPackageCommandRequest.ProtoReflect.Descriptor instead.
func (*DetectionPackageCommandRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{20}
}

func (x *DetectionPackageCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *DetectionPackageCommandRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DetectionPackageCommandRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *DetectionPackageCommandRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DetectionPackageCommandRequest) GetPackageUrl() string {
	if x != nil {
		return x.PackageUrl
	}
	return ""
}

func (x *DetectionPackageCommandRequest) GetSignatureUrl() string {
	if x != nil {
		return x.SignatureUrl
	}
	return ""
}

func (x *DetectionPackageCommandRequest) GetPackageSize() int64 {
	if x != nil {
		return x.PackageSize
	}
	return 0
}

func (x *DetectionPackageCommandRequest) GetRollback() bool {
	if x != nil {
		return x.Rollback
	}
	return false
}

type InstallDetectionPackageRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	HostId        string                          `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // empty means all online agents
	Command       *DetectionPackageCommandRequest `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallDetectionPackageRequest) Reset() {
	*x = InstallDetectionPackageRequest{}
	mi := &file_api_server_comm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallDetectionPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallDetectionPackageRequest) ProtoMessage() {}

func (x *InstallDetectionPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallDetectionPackageRequest.ProtoReflect.Descriptor instead.
func (*InstallDetectionPackageRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{21}
}

func (x *InstallDetectionPackageRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *InstallDetectionPackageRequest) GetCommand() *DetectionPackageCommandRequest {
	if x != nil {
		return x.Command
	}
	return nil
}

type InstallDetectionPackageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AffectedAgents int32                  `protobuf:"varint,2,opt,name=affected_agents,json=affectedAgents,proto3" json:"affected_agents,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstallDetectionPackageResponse) Reset() {
	*x = InstallDetectionPackageResponse{}
	mi := &file_api_server_comm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallDetectionPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallDetectionPackageResponse) ProtoMessage() {}

func (x *InstallDetectionPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallDetectionPackageResponse.ProtoReflect.Descriptor instead.
func (*InstallDetectionPackageResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{22}
}

func (x *InstallDetectionPackageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallDetectionPackageResponse) GetAffectedAgents() int32 {
	if x != nil {
		return x.AffectedAgents
	}
	return 0
}

func (x *InstallDetectionPackageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UninstallDetectionPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	PackageId     string                 `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallDetectionPackageRequest) Reset() {
	*x = UninstallDetectionPackageRequest{}
	mi := &file_api_server_comm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallDetectionPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallDetectionPackageRequest) ProtoMessage() {}

func (x *UninstallDetectionPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallDetectionPackageRequest.ProtoReflect.Descriptor instead.
func (*UninstallDetectionPackageRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{23}
}

func (x *UninstallDetectionPackageRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *UninstallDetectionPackageRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *UninstallDetectionPackageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UninstallDetectionPackageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AffectedAgents int32                  `protobuf:"varint,2,opt,name=affected_agents,json=affectedAgents,proto3" json:"affected_agents,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UninstallDetectionPackageResponse) Reset() {
	*x = UninstallDetectionPackageResponse{}
	mi := &file_api_server_comm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallDetectionPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallDetectionPackageResponse) ProtoMessage() {}

func (x *UninstallDetectionPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallDetectionPackageResponse.ProtoReflect.Descriptor instead.
func (*UninstallDetectionPackageResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{24}
}

func (x *UninstallDetectionPackageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UninstallDetectionPackageResponse) GetAffectedAgents() int32 {
	if x != nil {
		return x.AffectedAgents
	}
	return 0
}

func (x *UninstallDetectionPackageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SyncAgentConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // empty means all online agents
	Configs       []*AgentConfig         `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAgentConfigRequest) Reset() {
	*x = SyncAgentConfigRequest{}
	mi := &file_api_server_comm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAgentConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAgentConfigRequest) ProtoMessage() {}

func (x *SyncAgentConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAgentConfigRequest.ProtoReflect.Descriptor instead.
func (*SyncAgentConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{25}
}

func (x *SyncAgentConfigRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *SyncAgentConfigRequest) GetConfigs() []*AgentConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type AgentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigType    string                 `protobuf:"bytes,1,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_api_server_comm_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{26}
}

func (x *AgentConfig) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *AgentConfig) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type SyncAgentConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AffectedAgents int32                  `protobuf:"varint,2,opt,name=affected_agents,json=affectedAgents,proto3" json:"affected_agents,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncAgentConfigResponse) Reset() {
	*x = SyncAgentConfigResponse{}
	mi := &file_api_server_comm_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAgentConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAgentConfigResponse) ProtoMessage() {}

func (x *SyncAgentConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAgentConfigResponse.ProtoReflect.Descriptor instead.
func (*SyncAgentConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{27}
}

func (x *SyncAgentConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncAgentConfigResponse) GetAffectedAgents() int32 {
	if x != nil {
		return x.AffectedAgents
	}
	return 0
}

func (x *SyncAgentConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DetectionPackageHostStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostId         string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	PackageId      string                 `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ActiveArtifact string                 `protobuf:"bytes,5,opt,name=active_artifact,json=activeArtifact,proto3" json:"active_artifact,omitempty"` // ringbuf, perf
	LoadedHooks    []string               `protobuf:"bytes,6,rep,name=loaded_hooks,json=loadedHooks,proto3" json:"loaded_hooks,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ReportedAt     int64                  `protobuf:"varint,8,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetectionPackageHostStatus) Reset() {
	*x = DetectionPackageHostStatus{}
	mi := &file_api_server_comm_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionPackageHostStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionPackageHostStatus) ProtoMessage() {}

func (x *DetectionPackageHostStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionPackageHostStatus.ProtoReflect.Descriptor instead.
func (*DetectionPackageHostStatus) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{28}
}

func (x *DetectionPackageHostStatus) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *DetectionPackageHostStatus) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *DetectionPackageHostStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DetectionPackageHostStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DetectionPackageHostStatus) GetActiveArtifact() string {
	if x != nil {
		return x.ActiveArtifact
	}
	return ""
}

func (x *DetectionPackageHostStatus) GetLoadedHooks() []string {
	if x != nil {
		return x.LoadedHooks
	}
	return nil
}

func (x *DetectionPackageHostStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DetectionPackageHostStatus) GetReportedAt() int64 {
	if x != nil {
		return x.ReportedAt
	}
	return 0
}

type ReportDetectionPackageStatusRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Statuses      []*DetectionPackageHostStatus `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDetectionPackageStatusRequest) Reset() {
	*x = ReportDetectionPackageStatusRequest{}
	mi := &file_api_server_comm_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDetectionPackageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDetectionPackageStatusRequest) ProtoMessage() {}

func (x *ReportDetectionPackageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDetectionPackageStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportDetectionPackageStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{29}
}

func (x *ReportDetectionPackageStatusRequest) GetStatuses() []*DetectionPackageHostStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ReportDetectionPackageStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDetectionPackageStatusResponse) Reset() {
	*x = ReportDetectionPackageStatusResponse{}
	mi := &file_api_server_comm_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDetectionPackageStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDetectionPackageStatusResponse) ProtoMessage() {}

func (x *ReportDetectionPackageStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDetectionPackageStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportDetectionPackageStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{30}
}

func (x *ReportDetectionPackageStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportDetectionPackageStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportCorrelationAlertRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PackageId         string                 `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	CorrelationRuleId string                 `protobuf:"bytes,3,opt,name=correlation_rule_id,json=correlationRuleId,proto3" json:"correlation_rule_id,omitempty"`
	Severity          string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	EvidenceChainJson string                 `protobuf:"bytes,5,opt,name=evidence_chain_json,json=evidenceChainJson,proto3" json:"evidence_chain_json,omitempty"`
	EventDataJson     string                 `protobuf:"bytes,6,opt,name=event_data_json,json=eventDataJson,proto3" json:"event_data_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReportCorrelationAlertRequest) Reset() {
	*x = ReportCorrelationAlertRequest{}
	mi := &file_api_server_comm_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCorrelationAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCorrelationAlertRequest) ProtoMessage() {}

func (x *ReportCorrelationAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCorrelationAlertRequest.ProtoReflect.Descriptor instead.
func (*ReportCorrelationAlertRequest) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{31}
}

func (x *ReportCorrelationAlertRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportCorrelationAlertRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *ReportCorrelationAlertRequest) GetCorrelationRuleId() string {
	if x != nil {
		return x.CorrelationRuleId
	}
	return ""
}

func (x *ReportCorrelationAlertRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ReportCorrelationAlertRequest) GetEvidenceChainJson() string {
	if x != nil {
		return x.EvidenceChainJson
	}
	return ""
}

func (x *ReportCorrelationAlertRequest) GetEventDataJson() string {
	if x != nil {
		return x.EventDataJson
	}
	return ""
}

type ReportCorrelationAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCorrelationAlertResponse) Reset() {
	*x = ReportCorrelationAlertResponse{}
	mi := &file_api_server_comm_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCorrelationAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCorrelationAlertResponse) ProtoMessage() {}

func (x *ReportCorrelationAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_comm_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCorrelationAlertResponse.ProtoReflect.Descriptor instead.
func (*ReportCorrelationAlertResponse) Descriptor() ([]byte, []int) {
	return file_api_server_comm_proto_rawDescGZIP(), []int{32}
}

func (x *ReportCorrelationAlertResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_api_server_comm_proto protoreflect.FileDescriptor

const file_api_server_comm_proto_rawDesc = "" +
	"\n" +
	"\x15api_server_comm.proto\x12\x12api_server_comm.v1\"\xcf\x01\n" +
	"\x15ForwardCommandRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x17\n" +
	"\arule_id\x18\x03 \x01(\tR\x06ruleId\x12%\n" +
	"\x0escript_content\x18\x04 \x01(\tR\rscriptContent\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x1b\n" +
	"\ttask_type\x18\x06 \x01(\tR\btaskType\"e\n" +
	"\x16ForwardCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\"\xa1\x01\n" +
	"\x12ToolExecuteRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12\x1c\n" +
	"\targuments\x18\x04 \x01(\tR\targuments\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"\xa2\x01\n" +
	"\x13ToolExecuteResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\x03R\x0fexecutionTimeMs\"0\n" +
	"\x15GetAgentStatusRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\"\x9a\x02\n" +
	"\x16GetAgentStatusResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x17\n" +
	"\aos_type\x18\x05 \x01(\tR\x06osType\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x12%\n" +
	"\x0elast_heartbeat\x18\a \x01(\x03R\rlastHeartbeat\x12)\n" +
	"\x10pending_commands\x18\b \x01(\x05R\x0fpendingCommands\"r\n" +
	"\x1aListConnectedAgentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12#\n" +
	"\rstatus_filter\x18\x03 \x01(\tR\fstatusFilter\"\xb2\x01\n" +
	"\x1bListConnectedAgentsResponse\x125\n" +
	"\x06agents\x18\x01 \x03(\v2\x1d.api_server_comm.v1.AgentInfoR\x06agents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12!\n" +
	"\fonline_count\x18\x03 \x01(\x05R\vonlineCount\x12#\n" +
	"\roffline_count\x18\x04 \x01(\x05R\fofflineCount\"\xba\x02\n" +
	"\tAgentInfo\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x17\n" +
	"\aos_type\x18\x04 \x01(\tR\x06osType\x12\x1d\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tR\tosVersion\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x12\x12\n" +
	"\x04arch\x18\a \x01(\tR\x04arch\x12\x1c\n" +
	"\tconnected\x18\b \x01(\bR\tconnected\x12%\n" +
	"\x0elast_heartbeat\x18\t \x01(\x03R\rlastHeartbeat\x12#\n" +
	"\rregistered_at\x18\n" +
	" \x01(\x03R\fregisteredAt\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xed\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12N\n" +
	"\adetails\x18\x04 \x03(\v24.api_server_comm.v1.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\x17UpdateAgentRulesRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x129\n" +
	"\x05rules\x18\x03 \x03(\v2#.api_server_comm.v1.AgentRuleUpdateR\x05rules\"\\\n" +
	"\x0fAgentRuleUpdate\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"w\n" +
	"\x18UpdateAgentRulesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0faffected_agents\x18\x02 \x01(\x05R\x0eaffectedAgents\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb7\x01\n" +
	"\x1aExecuteBlockCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x19\n" +
	"\balert_id\x18\x06 \x01(\tR\aalertId\"\x8d\x01\n" +
	"\x1bExecuteBlockCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vexecuted_at\x18\x04 \x01(\x03R\n" +
	"executedAt\"1\n" +
	"\x16CollectSoftwareRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\"n\n" +
	"\x17CollectSoftwareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rsoftware_json\x18\x02 \x01(\tR\fsoftwareJson\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xd3\x01\n" +
	"\x19CommandResultNotification\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x19\n" +
	"\bis_final\x18\x06 \x01(\bR\aisFinal\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"\xc2\x01\n" +
	"\x1dAgentStatusChangeNotification\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12'\n" +
	"\x0fprevious_status\x18\x03 \x01(\tR\x0epreviousStatus\x12%\n" +
	"\x0ecurrent_status\x18\x04 \x01(\tR\rcurrentStatus\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x8e\x02\n" +
	"\x17DetectionPackageCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"package_id\x18\x03 \x01(\tR\tpackageId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1f\n" +
	"\vpackage_url\x18\x05 \x01(\tR\n" +
	"packageUrl\x12#\n" +
	"\rsignature_url\x18\x06 \x01(\tR\fsignatureUrl\x12!\n" +
	"\fpackage_size\x18\a \x01(\x03R\vpackageSize\x12\x1a\n" +
	"\brollback\x18\b \x01(\bR\brollback\"\x80\x01\n" +
	"\x1eInstallDetectionPackageRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12E\n" +
	"\acommand\x18\x02 \x01(\v2+.api_server_comm.v1.DetectionPackageCommandRequestR\acommand\"~\n" +
	"\x1fInstallDetectionPackageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0faffected_agents\x18\x02 \x01(\x05R\x0eaffectedAgents\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"t\n" +
	" UninstallDetectionPackageRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x80\x01\n" +
	"!UninstallDetectionPackageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0faffected_agents\x18\x02 \x01(\x05R\x0eaffectedAgents\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"l\n" +
	"\x16SyncAgentConfigRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x129\n" +
	"\aconfigs\x18\x02 \x03(\v2\x1f.api_server_comm.v1.AgentConfigR\aconfigs\"O\n" +
	"\vAgentConfig\x12\x1f\n" +
	"\vconfig_type\x18\x01 \x01(\tR\n" +
	"configType\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\"v\n" +
	"\x17SyncAgentConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0faffected_agents\x18\x02 \x01(\x05R\x0eaffectedAgents\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x98\x02\n" +
	"\x1aDetectionPackageHostStatus\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12'\n" +
	"\x0factive_artifact\x18\x05 \x01(\tR\x0eactiveArtifact\x12!\n" +
	"\floaded_hooks\x18\x06 \x03(\tR\vloadedHooks\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vreported_at\x18\b \x01(\x03R\n" +
	"reportedAt\"q\n" +
	"#ReportDetectionPackageStatusRequest\x12J\n" +
	"\bstatuses\x18\x01 \x03(\v2..api_server_comm.v1.DetectionPackageHostStatusR\bstatuses\"Z\n" +
	"$ReportDetectionPackageStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfd\x01\n" +
	"\x1dReportCorrelationAlertRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x12.\n" +
	"\x13correlation_rule_id\x18\x03 \x01(\tR\x11correlationRuleId\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12.\n" +
	"\x13evidence_chain_json\x18\x05 \x01(\tR\x11evidenceChainJson\x12&\n" +
	"\x0fevent_data_json\x18\x06 \x01(\tR\reventDataJson\"<\n" +
	"\x1eReportCorrelationAlertResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\x81\f\n" +
	"\x11APIServerToServer\x12g\n" +
	"\x0eForwardCommand\x12).api_server_comm.v1.ForwardCommandRequest\x1a*.api_server_comm.v1.ForwardCommandResponse\x12^\n" +
	"\vExecuteTool\x12&.api_server_comm.v1.ToolExecuteRequest\x1a'.api_server_comm.v1.ToolExecuteResponse\x12g\n" +
	"\x0eGetAgentStatus\x12).api_server_comm.v1.GetAgentStatusRequest\x1a*.api_server_comm.v1.GetAgentStatusResponse\x12v\n" +
	"\x13ListConnectedAgents\x12..api_server_comm.v1.ListConnectedAgentsRequest\x1a/.api_server_comm.v1.ListConnectedAgentsResponse\x12^\n" +
	"\vHealthCheck\x12&.api_server_comm.v1.HealthCheckRequest\x1a'.api_server_comm.v1.HealthCheckResponse\x12m\n" +
	"\x10UpdateAgentRules\x12+.api_server_comm.v1.UpdateAgentRulesRequest\x1a,.api_server_comm.v1.UpdateAgentRulesResponse\x12v\n" +
	"\x13ExecuteBlockCommand\x12..api_server_comm.v1.ExecuteBlockCommandRequest\x1a/.api_server_comm.v1.ExecuteBlockCommandResponse\x12j\n" +
	"\x0fCollectSoftware\x12*.api_server_comm.v1.CollectSoftwareRequest\x1a+.api_server_comm.v1.CollectSoftwareResponse\x12\x82\x01\n" +
	"\x17InstallDetectionPackage\x122.api_server_comm.v1.InstallDetectionPackageRequest\x1a3.api_server_comm.v1.InstallDetectionPackageResponse\x12\x88\x01\n" +
	"\x19UninstallDetectionPackage\x124.api_server_comm.v1.UninstallDetectionPackageRequest\x1a5.api_server_comm.v1.UninstallDetectionPackageResponse\x12j\n" +
	"\x0fSyncAgentConfig\x12*.api_server_comm.v1.SyncAgentConfigRequest\x1a+.api_server_comm.v1.SyncAgentConfigResponse\x12\x91\x01\n" +
	"\x1cReportDetectionPackageStatus\x127.api_server_comm.v1.ReportDetectionPackageStatusRequest\x1a8.api_server_comm.v1.ReportDetectionPackageStatusResponse\x12\x7f\n" +
	"\x16ReportCorrelationAlert\x121.api_server_comm.v1.ReportCorrelationAlertRequest\x1a2.api_server_comm.v1.ReportCorrelationAlertResponseB\x1aZ\x18api-server/pkg/api/v1;pbb\x06proto3"

var (
	file_api_server_comm_proto_rawDescOnce sync.Once
	file_api_server_comm_proto_rawDescData []byte
)

func file_api_server_comm_proto_rawDescGZIP() []byte {
	file_api_server_comm_proto_rawDescOnce.Do(func() {
		file_api_server_comm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_server_comm_proto_rawDesc), len(file_api_server_comm_proto_rawDesc)))
	})
	return file_api_server_comm_proto_rawDescData
}

var file_api_server_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_server_comm_proto_goTypes = []any{
	(*ForwardCommandRequest)(nil),                // 0: api_server_comm.v1.ForwardCommandRequest
	(*ForwardCommandResponse)(nil),               // 1: api_server_comm.v1.ForwardCommandResponse
	(*ToolExecuteRequest)(nil),                   // 2: api_server_comm.v1.ToolExecuteRequest
	(*ToolExecuteResponse)(nil),                  // 3: api_server_comm.v1.ToolExecuteResponse
	(*GetAgentStatusRequest)(nil),                // 4: api_server_comm.v1.GetAgentStatusRequest
	(*GetAgentStatusResponse)(nil),               // 5: api_server_comm.v1.GetAgentStatusResponse
	(*ListConnectedAgentsRequest)(nil),           // 6: api_server_comm.v1.ListConnectedAgentsRequest
	(*ListConnectedAgentsResponse)(nil),          // 7: api_server_comm.v1.ListConnectedAgentsResponse
	(*AgentInfo)(nil),                            // 8: api_server_comm.v1.AgentInfo
	(*HealthCheckRequest)(nil),                   // 9: api_server_comm.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),                  // 10: api_server_comm.v1.HealthCheckResponse
	(*UpdateAgentRulesRequest)(nil),              // 11: api_server_comm.v1.UpdateAgentRulesRequest
	(*AgentRuleUpdate)(nil),                      // 12: api_server_comm.v1.AgentRuleUpdate
	(*UpdateAgentRulesResponse)(nil),             // 13: api_server_comm.v1.UpdateAgentRulesResponse
	(*ExecuteBlockCommandRequest)(nil),           // 14: api_server_comm.v1.ExecuteBlockCommandRequest
	(*ExecuteBlockCommandResponse)(nil),          // 15: api_server_comm.v1.ExecuteBlockCommandResponse
	(*CollectSoftwareRequest)(nil),               // 16: api_server_comm.v1.CollectSoftwareRequest
	(*CollectSoftwareResponse)(nil),              // 17: api_server_comm.v1.CollectSoftwareResponse
	(*CommandResultNotification)(nil),            // 18: api_server_comm.v1.CommandResultNotification
	(*AgentStatusChangeNotification)(nil),        // 19: api_server_comm.v1.AgentStatusChangeNotification
	(*DetectionPackageCommandRequest)(nil),       // 20: api_server_comm.v1.DetectionPackageCommandRequest
	(*InstallDetectionPackageRequest)(nil),       // 21: api_server_comm.v1.InstallDetectionPackageRequest
	(*InstallDetectionPackageResponse)(nil),      // 22: api_server_comm.v1.InstallDetectionPackageResponse
	(*UninstallDetectionPackageRequest)(nil),     // 23: api_server_comm.v1.UninstallDetectionPackageRequest
	(*UninstallDetectionPackageResponse)(nil),    // 24: api_server_comm.v1.UninstallDetectionPackageResponse
	(*SyncAgentConfigRequest)(nil),               // 25: api_server_comm.v1.SyncAgentConfigRequest
	(*AgentConfig)(nil),                          // 26: api_server_comm.v1.AgentConfig
	(*SyncAgentConfigResponse)(nil),              // 27: api_server_comm.v1.SyncAgentConfigResponse
	(*DetectionPackageHostStatus)(nil),           // 28: api_server_comm.v1.DetectionPackageHostStatus
	(*ReportDetectionPackageStatusRequest)(nil),  // 29: api_server_comm.v1.ReportDetectionPackageStatusRequest
	(*ReportDetectionPackageStatusResponse)(nil), // 30: api_server_comm.v1.ReportDetectionPackageStatusResponse
	(*ReportCorrelationAlertRequest)(nil),        // 31: api_server_comm.v1.ReportCorrelationAlertRequest
	(*ReportCorrelationAlertResponse)(nil),       // 32: api_server_comm.v1.ReportCorrelationAlertResponse
	nil,                                          // 33: api_server_comm.v1.HealthCheckResponse.DetailsEntry
}
var file_api_server_comm_proto_depIdxs = []int32{
	8,  // 0: api_server_comm.v1.ListConnectedAgentsResponse.agents:type_name -> api_server_comm.v1.AgentInfo
	33, // 1: api_server_comm.v1.HealthCheckResponse.details:type_name -> api_server_comm.v1.HealthCheckResponse.DetailsEntry
	12, // 2: api_server_comm.v1.UpdateAgentRulesRequest.rules:type_name -> api_server_comm.v1.AgentRuleUpdate
	20, // 3: api_server_comm.v1.InstallDetectionPackageRequest.command:type_name -> api_server_comm.v1.DetectionPackageCommandRequest
	26, // 4: api_server_comm.v1.SyncAgentConfigRequest.configs:type_name -> api_server_comm.v1.AgentConfig
	28, // 5: api_server_comm.v1.ReportDetectionPackageStatusRequest.statuses:type_name -> api_server_comm.v1.DetectionPackageHostStatus
	0,  // 6: api_server_comm.v1.APIServerToServer.ForwardCommand:input_type -> api_server_comm.v1.ForwardCommandRequest
	2,  // 7: api_server_comm.v1.APIServerToServer.ExecuteTool:input_type -> api_server_comm.v1.ToolExecuteRequest
	4,  // 8: api_server_comm.v1.APIServerToServer.GetAgentStatus:input_type -> api_server_comm.v1.GetAgentStatusRequest
	6,  // 9: api_server_comm.v1.APIServerToServer.ListConnectedAgents:input_type -> api_server_comm.v1.ListConnectedAgentsRequest
	9,  // 10: api_server_comm.v1.APIServerToServer.HealthCheck:input_type -> api_server_comm.v1.HealthCheckRequest
	11, // 11: api_server_comm.v1.APIServerToServer.UpdateAgentRules:input_type -> api_server_comm.v1.UpdateAgentRulesRequest
	14, // 12: api_server_comm.v1.APIServerToServer.ExecuteBlockCommand:input_type -> api_server_comm.v1.ExecuteBlockCommandRequest
	16, // 13: api_server_comm.v1.APIServerToServer.CollectSoftware:input_type -> api_server_comm.v1.CollectSoftwareRequest
	21, // 14: api_server_comm.v1.APIServerToServer.InstallDetectionPackage:input_type -> api_server_comm.v1.InstallDetectionPackageRequest
	23, // 15: api_server_comm.v1.APIServerToServer.UninstallDetectionPackage:input_type -> api_server_comm.v1.UninstallDetectionPackageRequest
	25, // 16: api_server_comm.v1.APIServerToServer.SyncAgentConfig:input_type -> api_server_comm.v1.SyncAgentConfigRequest
	29, // 17: api_server_comm.v1.APIServerToServer.ReportDetectionPackageStatus:input_type -> api_server_comm.v1.ReportDetectionPackageStatusRequest
	31, // 18: api_server_comm.v1.APIServerToServer.ReportCorrelationAlert:input_type -> api_server_comm.v1.ReportCorrelationAlertRequest
	1,  // 19: api_server_comm.v1.APIServerToServer.ForwardCommand:output_type -> api_server_comm.v1.ForwardCommandResponse
	3,  // 20: api_server_comm.v1.APIServerToServer.ExecuteTool:output_type -> api_server_comm.v1.ToolExecuteResponse
	5,  // 21: api_server_comm.v1.APIServerToServer.GetAgentStatus:output_type -> api_server_comm.v1.GetAgentStatusResponse
	7,  // 22: api_server_comm.v1.APIServerToServer.ListConnectedAgents:output_type -> api_server_comm.v1.ListConnectedAgentsResponse
	10, // 23: api_server_comm.v1.APIServerToServer.HealthCheck:output_type -> api_server_comm.v1.HealthCheckResponse
	13, // 24: api_server_comm.v1.APIServerToServer.UpdateAgentRules:output_type -> api_server_comm.v1.UpdateAgentRulesResponse
	15, // 25: api_server_comm.v1.APIServerToServer.ExecuteBlockCommand:output_type -> api_server_comm.v1.ExecuteBlockCommandResponse
	17, // 26: api_server_comm.v1.APIServerToServer.CollectSoftware:output_type -> api_server_comm.v1.CollectSoftwareResponse
	22, // 27: api_server_comm.v1.APIServerToServer.InstallDetectionPackage:output_type -> api_server_comm.v1.InstallDetectionPackageResponse
	24, // 28: api_server_comm.v1.APIServerToServer.UninstallDetectionPackage:output_type -> api_server_comm.v1.UninstallDetectionPackageResponse
	27, // 29: api_server_comm.v1.APIServerToServer.SyncAgentConfig:output_type -> api_server_comm.v1.SyncAgentConfigResponse
	30, // 30: api_server_comm.v1.APIServerToServer.ReportDetectionPackageStatus:output_type -> api_server_comm.v1.ReportDetectionPackageStatusResponse
	32, // 31: api_server_comm.v1.APIServerToServer.ReportCorrelationAlert:output_type -> api_server_comm.v1.ReportCorrelationAlertResponse
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_server_comm_proto_init() }
func file_api_server_comm_proto_init() {
	if File_api_server_comm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_server_comm_proto_rawDesc), len(file_api_server_comm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_server_comm_proto_goTypes,
		DependencyIndexes: file_api_server_comm_proto_depIdxs,
		MessageInfos:      file_api_server_comm_proto_msgTypes,
	}.Build()
	File_api_server_comm_proto = out.File
	file_api_server_comm_proto_goTypes = nil
	file_api_server_comm_proto_depIdxs = nil
}
