// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.24.4
// source: api_server_comm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	APIServerToServer_ForwardCommand_FullMethodName               = "/api_server_comm.v1.APIServerToServer/ForwardCommand"
	APIServerToServer_ExecuteTool_FullMethodName                  = "/api_server_comm.v1.APIServerToServer/ExecuteTool"
	APIServerToServer_GetAgentStatus_FullMethodName               = "/api_server_comm.v1.APIServerToServer/GetAgentStatus"
	APIServerToServer_ListConnectedAgents_FullMethodName          = "/api_server_comm.v1.APIServerToServer/ListConnectedAgents"
	APIServerToServer_HealthCheck_FullMethodName                  = "/api_server_comm.v1.APIServerToServer/HealthCheck"
	APIServerToServer_UpdateAgentRules_FullMethodName             = "/api_server_comm.v1.APIServerToServer/UpdateAgentRules"
	APIServerToServer_ExecuteBlockCommand_FullMethodName          = "/api_server_comm.v1.APIServerToServer/ExecuteBlockCommand"
	APIServerToServer_CollectSoftware_FullMethodName              = "/api_server_comm.v1.APIServerToServer/CollectSoftware"
	APIServerToServer_InstallDetectionPackage_FullMethodName      = "/api_server_comm.v1.APIServerToServer/InstallDetectionPackage"
	APIServerToServer_UninstallDetectionPackage_FullMethodName    = "/api_server_comm.v1.APIServerToServer/UninstallDetectionPackage"
	APIServerToServer_SyncAgentConfig_FullMethodName              = "/api_server_comm.v1.APIServerToServer/SyncAgentConfig"
	APIServerToServer_ReportDetectionPackageStatus_FullMethodName = "/api_server_comm.v1.APIServerToServer/ReportDetectionPackageStatus"
	APIServerToServer_ReportCorrelationAlert_FullMethodName       = "/api_server_comm.v1.APIServerToServer/ReportCorrelationAlert"
)

// APIServerToServerClient is the client API for APIServerToServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// APIServerToServer 服务定义
// API Server 作为 gRPC 客户端调用 Server
type APIServerToServerClient interface {
	// ForwardCommand 转发命令到Agent
	ForwardCommand(ctx context.Context, in *ForwardCommandRequest, opts ...grpc.CallOption) (*ForwardCommandResponse, error)
	// ExecuteTool 同步执行工具并等待结果
	ExecuteTool(ctx context.Context, in *ToolExecuteRequest, opts ...grpc.CallOption) (*ToolExecuteResponse, error)
	// GetAgentStatus 获取单个Agent状态
	GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*GetAgentStatusResponse, error)
	// ListConnectedAgents 列出所有已连接的Agent
	ListConnectedAgents(ctx context.Context, in *ListConnectedAgentsRequest, opts ...grpc.CallOption) (*ListConnectedAgentsResponse, error)
	// HealthCheck 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// UpdateAgentRules 更新Agent的Sigma规则
	UpdateAgentRules(ctx context.Context, in *UpdateAgentRulesRequest, opts ...grpc.CallOption) (*UpdateAgentRulesResponse, error)
	// ExecuteBlockCommand 执行阻断命令
	ExecuteBlockCommand(ctx context.Context, in *ExecuteBlockCommandRequest, opts ...grpc.CallOption) (*ExecuteBlockCommandResponse, error)
	// CollectSoftware 收集主机软件清单
	CollectSoftware(ctx context.Context, in *CollectSoftwareRequest, opts ...grpc.CallOption) (*CollectSoftwareResponse, error)
	// V5.8 Detection Package Management
	InstallDetectionPackage(ctx context.Context, in *InstallDetectionPackageRequest, opts ...grpc.CallOption) (*InstallDetectionPackageResponse, error)
	UninstallDetectionPackage(ctx context.Context, in *UninstallDetectionPackageRequest, opts ...grpc.CallOption) (*UninstallDetectionPackageResponse, error)
	SyncAgentConfig(ctx context.Context, in *SyncAgentConfigRequest, opts ...grpc.CallOption) (*SyncAgentConfigResponse, error)
	ReportDetectionPackageStatus(ctx context.Context, in *ReportDetectionPackageStatusRequest, opts ...grpc.CallOption) (*ReportDetectionPackageStatusResponse, error)
	ReportCorrelationAlert(ctx context.Context, in *ReportCorrelationAlertRequest, opts ...grpc.CallOption) (*ReportCorrelationAlertResponse, error)
}

type aPIServerToServerClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIServerToServerClient(cc grpc.ClientConnInterface) APIServerToServerClient {
	return &aPIServerToServerClient{cc}
}

func (c *aPIServerToServerClient) ForwardCommand(ctx context.Context, in *ForwardCommandRequest, opts ...grpc.CallOption) (*ForwardCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardCommandResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_ForwardCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) ExecuteTool(ctx context.Context, in *ToolExecuteRequest, opts ...grpc.CallOption) (*ToolExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolExecuteResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*GetAgentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentStatusResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_GetAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) ListConnectedAgents(ctx context.Context, in *ListConnectedAgentsRequest, opts ...grpc.CallOption) (*ListConnectedAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectedAgentsResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_ListConnectedAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) UpdateAgentRules(ctx context.Context, in *UpdateAgentRulesRequest, opts ...grpc.CallOption) (*UpdateAgentRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAgentRulesResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_UpdateAgentRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) ExecuteBlockCommand(ctx context.Context, in *ExecuteBlockCommandRequest, opts ...grpc.CallOption) (*ExecuteBlockCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteBlockCommandResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_ExecuteBlockCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) CollectSoftware(ctx context.Context, in *CollectSoftwareRequest, opts ...grpc.CallOption) (*CollectSoftwareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectSoftwareResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_CollectSoftware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) InstallDetectionPackage(ctx context.Context, in *InstallDetectionPackageRequest, opts ...grpc.CallOption) (*InstallDetectionPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallDetectionPackageResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_InstallDetectionPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) UninstallDetectionPackage(ctx context.Context, in *UninstallDetectionPackageRequest, opts ...grpc.CallOption) (*UninstallDetectionPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UninstallDetectionPackageResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_UninstallDetectionPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) SyncAgentConfig(ctx context.Context, in *SyncAgentConfigRequest, opts ...grpc.CallOption) (*SyncAgentConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncAgentConfigResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_SyncAgentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) ReportDetectionPackageStatus(ctx context.Context, in *ReportDetectionPackageStatusRequest, opts ...grpc.CallOption) (*ReportDetectionPackageStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportDetectionPackageStatusResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_ReportDetectionPackageStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerToServerClient) ReportCorrelationAlert(ctx context.Context, in *ReportCorrelationAlertRequest, opts ...grpc.CallOption) (*ReportCorrelationAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportCorrelationAlertResponse)
	err := c.cc.Invoke(ctx, APIServerToServer_ReportCorrelationAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServerToServerServer is the server API for APIServerToServer service.
// All implementations must embed UnimplementedAPIServerToServerServer
// for forward compatibility.
//
// APIServerToServer 服务定义
// API Server 作为 gRPC 客户端调用 Server
type APIServerToServerServer interface {
	// ForwardCommand 转发命令到Agent
	ForwardCommand(context.Context, *ForwardCommandRequest) (*ForwardCommandResponse, error)
	// ExecuteTool 同步执行工具并等待结果
	ExecuteTool(context.Context, *ToolExecuteRequest) (*ToolExecuteResponse, error)
	// GetAgentStatus 获取单个Agent状态
	GetAgentStatus(context.Context, *GetAgentStatusRequest) (*GetAgentStatusResponse, error)
	// ListConnectedAgents 列出所有已连接的Agent
	ListConnectedAgents(context.Context, *ListConnectedAgentsRequest) (*ListConnectedAgentsResponse, error)
	// HealthCheck 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// UpdateAgentRules 更新Agent的Sigma规则
	UpdateAgentRules(context.Context, *UpdateAgentRulesRequest) (*UpdateAgentRulesResponse, error)
	// ExecuteBlockCommand 执行阻断命令
	ExecuteBlockCommand(context.Context, *ExecuteBlockCommandRequest) (*ExecuteBlockCommandResponse, error)
	// CollectSoftware 收集主机软件清单
	CollectSoftware(context.Context, *CollectSoftwareRequest) (*CollectSoftwareResponse, error)
	// V5.8 Detection Package Management
	InstallDetectionPackage(context.Context, *InstallDetectionPackageRequest) (*InstallDetectionPackageResponse, error)
	UninstallDetectionPackage(context.Context, *UninstallDetectionPackageRequest) (*UninstallDetectionPackageResponse, error)
	SyncAgentConfig(context.Context, *SyncAgentConfigRequest) (*SyncAgentConfigResponse, error)
	ReportDetectionPackageStatus(context.Context, *ReportDetectionPackageStatusRequest) (*ReportDetectionPackageStatusResponse, error)
	ReportCorrelationAlert(context.Context, *ReportCorrelationAlertRequest) (*ReportCorrelationAlertResponse, error)
	mustEmbedUnimplementedAPIServerToServerServer()
}

// UnimplementedAPIServerToServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIServerToServerServer struct{}

func (UnimplementedAPIServerToServerServer) ForwardCommand(context.Context, *ForwardCommandRequest) (*ForwardCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardCommand not implemented")
}
func (UnimplementedAPIServerToServerServer) ExecuteTool(context.Context, *ToolExecuteRequest) (*ToolExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedAPIServerToServerServer) GetAgentStatus(context.Context, *GetAgentStatusRequest) (*GetAgentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentStatus not implemented")
}
func (UnimplementedAPIServerToServerServer) ListConnectedAgents(context.Context, *ListConnectedAgentsRequest) (*ListConnectedAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnectedAgents not implemented")
}
func (UnimplementedAPIServerToServerServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAPIServerToServerServer) UpdateAgentRules(context.Context, *UpdateAgentRulesRequest) (*UpdateAgentRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgentRules not implemented")
}
func (UnimplementedAPIServerToServerServer) ExecuteBlockCommand(context.Context, *ExecuteBlockCommandRequest) (*ExecuteBlockCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteBlockCommand not implemented")
}
func (UnimplementedAPIServerToServerServer) CollectSoftware(context.Context, *CollectSoftwareRequest) (*CollectSoftwareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectSoftware not implemented")
}
func (UnimplementedAPIServerToServerServer) InstallDetectionPackage(context.Context, *InstallDetectionPackageRequest) (*InstallDetectionPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallDetectionPackage not implemented")
}
func (UnimplementedAPIServerToServerServer) UninstallDetectionPackage(context.Context, *UninstallDetectionPackageRequest) (*UninstallDetectionPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UninstallDetectionPackage not implemented")
}
func (UnimplementedAPIServerToServerServer) SyncAgentConfig(context.Context, *SyncAgentConfigRequest) (*SyncAgentConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncAgentConfig not implemented")
}
func (UnimplementedAPIServerToServerServer) ReportDetectionPackageStatus(context.Context, *ReportDetectionPackageStatusRequest) (*ReportDetectionPackageStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDetectionPackageStatus not implemented")
}
func (UnimplementedAPIServerToServerServer) ReportCorrelationAlert(context.Context, *ReportCorrelationAlertRequest) (*ReportCorrelationAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCorrelationAlert not implemented")
}
func (UnimplementedAPIServerToServerServer) mustEmbedUnimplementedAPIServerToServerServer() {}
func (UnimplementedAPIServerToServerServer) testEmbeddedByValue()                           {}

// UnsafeAPIServerToServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServerToServerServer will
// result in compilation errors.
type UnsafeAPIServerToServerServer interface {
	mustEmbedUnimplementedAPIServerToServerServer()
}

func RegisterAPIServerToServerServer(s grpc.ServiceRegistrar, srv APIServerToServerServer) {
	// If the following call panics, it indicates UnimplementedAPIServerToServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&APIServerToServer_ServiceDesc, srv)
}

func _APIServerToServer_ForwardCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).ForwardCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_ForwardCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).ForwardCommand(ctx, req.(*ForwardCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).ExecuteTool(ctx, req.(*ToolExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_GetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).GetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_GetAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).GetAgentStatus(ctx, req.(*GetAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_ListConnectedAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectedAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).ListConnectedAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_ListConnectedAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).ListConnectedAgents(ctx, req.(*ListConnectedAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_UpdateAgentRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).UpdateAgentRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_UpdateAgentRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).UpdateAgentRules(ctx, req.(*UpdateAgentRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_ExecuteBlockCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteBlockCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).ExecuteBlockCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_ExecuteBlockCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).ExecuteBlockCommand(ctx, req.(*ExecuteBlockCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_CollectSoftware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectSoftwareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).CollectSoftware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_CollectSoftware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).CollectSoftware(ctx, req.(*CollectSoftwareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_InstallDetectionPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallDetectionPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).InstallDetectionPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_InstallDetectionPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).InstallDetectionPackage(ctx, req.(*InstallDetectionPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_UninstallDetectionPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallDetectionPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).UninstallDetectionPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_UninstallDetectionPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).UninstallDetectionPackage(ctx, req.(*UninstallDetectionPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_SyncAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncAgentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).SyncAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_SyncAgentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).SyncAgentConfig(ctx, req.(*SyncAgentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_ReportDetectionPackageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDetectionPackageStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).ReportDetectionPackageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_ReportDetectionPackageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).ReportDetectionPackageStatus(ctx, req.(*ReportDetectionPackageStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServerToServer_ReportCorrelationAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportCorrelationAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerToServerServer).ReportCorrelationAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIServerToServer_ReportCorrelationAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerToServerServer).ReportCorrelationAlert(ctx, req.(*ReportCorrelationAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// APIServerToServer_ServiceDesc is the grpc.ServiceDesc for APIServerToServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIServerToServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api_server_comm.v1.APIServerToServer",
	HandlerType: (*APIServerToServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardCommand",
			Handler:    _APIServerToServer_ForwardCommand_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _APIServerToServer_ExecuteTool_Handler,
		},
		{
			MethodName: "GetAgentStatus",
			Handler:    _APIServerToServer_GetAgentStatus_Handler,
		},
		{
			MethodName: "ListConnectedAgents",
			Handler:    _APIServerToServer_ListConnectedAgents_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _APIServerToServer_HealthCheck_Handler,
		},
		{
			MethodName: "UpdateAgentRules",
			Handler:    _APIServerToServer_UpdateAgentRules_Handler,
		},
		{
			MethodName: "ExecuteBlockCommand",
			Handler:    _APIServerToServer_ExecuteBlockCommand_Handler,
		},
		{
			MethodName: "CollectSoftware",
			Handler:    _APIServerToServer_CollectSoftware_Handler,
		},
		{
			MethodName: "InstallDetectionPackage",
			Handler:    _APIServerToServer_InstallDetectionPackage_Handler,
		},
		{
			MethodName: "UninstallDetectionPackage",
			Handler:    _APIServerToServer_UninstallDetectionPackage_Handler,
		},
		{
			MethodName: "SyncAgentConfig",
			Handler:    _APIServerToServer_SyncAgentConfig_Handler,
		},
		{
			MethodName: "ReportDetectionPackageStatus",
			Handler:    _APIServerToServer_ReportDetectionPackageStatus_Handler,
		},
		{
			MethodName: "ReportCorrelationAlert",
			Handler:    _APIServerToServer_ReportCorrelationAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_server_comm.proto",
}
