// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: proto/agent_comm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssetInfo 资产信息
type AssetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsType        string                 `protobuf:"bytes,3,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetInfo) Reset() {
	*x = AssetInfo{}
	mi := &file_proto_agent_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetInfo) ProtoMessage() {}

func (x *AssetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetInfo.ProtoReflect.Descriptor instead.
func (*AssetInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{0}
}

func (x *AssetInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AssetInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AssetInfo) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *AssetInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *AssetInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AssetInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// RegisterRequest 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	AssetInfo     *AssetInfo             `protobuf:"bytes,2,opt,name=asset_info,json=assetInfo,proto3" json:"asset_info,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	CallbackPort  int32                  `protobuf:"varint,4,opt,name=callback_port,json=callbackPort,proto3" json:"callback_port,omitempty"` // Agent's gRPC callback port for Server to call back
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_agent_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterRequest) GetAssetInfo() *AssetInfo {
	if x != nil {
		return x.AssetInfo
	}
	return nil
}

func (x *RegisterRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterRequest) GetCallbackPort() int32 {
	if x != nil {
		return x.CallbackPort
	}
	return 0
}

// RegisterResponse 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_agent_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HeartbeatRequest 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_comm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HeartbeatResponse 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_comm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CommandExecute 命令执行
type CommandExecute struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RuleId         string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	HostId         string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ScriptContent  string                 `protobuf:"bytes,4,opt,name=script_content,json=scriptContent,proto3" json:"script_content,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandExecute) Reset() {
	*x = CommandExecute{}
	mi := &file_proto_agent_comm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExecute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecute) ProtoMessage() {}

func (x *CommandExecute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecute.ProtoReflect.Descriptor instead.
func (*CommandExecute) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{5}
}

func (x *CommandExecute) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CommandExecute) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *CommandExecute) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CommandExecute) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

func (x *CommandExecute) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// CommandResult 命令结果
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	IsFinal       bool                   `protobuf:"varint,6,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_agent_comm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CommandResult) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// CommandRequest 命令请求
type CommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*CommandRequest_Execute
	//	*CommandRequest_Result
	//	*CommandRequest_RuleUpdate
	//	*CommandRequest_Block
	//	*CommandRequest_ConfigSync
	//	*CommandRequest_DetectionPackage
	Request       isCommandRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_agent_comm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{7}
}

func (x *CommandRequest) GetRequest() isCommandRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CommandRequest) GetExecute() *CommandExecute {
	if x != nil {
		if x, ok := x.Request.(*CommandRequest_Execute); ok {
			return x.Execute
		}
	}
	return nil
}

func (x *CommandRequest) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Request.(*CommandRequest_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *CommandRequest) GetRuleUpdate() *RuleUpdateRequest {
	if x != nil {
		if x, ok := x.Request.(*CommandRequest_RuleUpdate); ok {
			return x.RuleUpdate
		}
	}
	return nil
}

func (x *CommandRequest) GetBlock() *BlockCommand {
	if x != nil {
		if x, ok := x.Request.(*CommandRequest_Block); ok {
			return x.Block
		}
	}
	return nil
}

func (x *CommandRequest) GetConfigSync() *ConfigSync {
	if x != nil {
		if x, ok := x.Request.(*CommandRequest_ConfigSync); ok {
			return x.ConfigSync
		}
	}
	return nil
}

func (x *CommandRequest) GetDetectionPackage() *DetectionPackageCommand {
	if x != nil {
		if x, ok := x.Request.(*CommandRequest_DetectionPackage); ok {
			return x.DetectionPackage
		}
	}
	return nil
}

type isCommandRequest_Request interface {
	isCommandRequest_Request()
}

type CommandRequest_Execute struct {
	Execute *CommandExecute `protobuf:"bytes,1,opt,name=execute,proto3,oneof"`
}

type CommandRequest_Result struct {
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type CommandRequest_RuleUpdate struct {
	RuleUpdate *RuleUpdateRequest `protobuf:"bytes,3,opt,name=rule_update,json=ruleUpdate,proto3,oneof"`
}

type CommandRequest_Block struct {
	Block *BlockCommand `protobuf:"bytes,4,opt,name=block,proto3,oneof"`
}

type CommandRequest_ConfigSync struct {
	ConfigSync *ConfigSync `protobuf:"bytes,5,opt,name=config_sync,json=configSync,proto3,oneof"`
}

type CommandRequest_DetectionPackage struct {
	DetectionPackage *DetectionPackageCommand `protobuf:"bytes,6,opt,name=detection_package,json=detectionPackage,proto3,oneof"` // V5.8
}

func (*CommandRequest_Execute) isCommandRequest_Request() {}

func (*CommandRequest_Result) isCommandRequest_Request() {}

func (*CommandRequest_RuleUpdate) isCommandRequest_Request() {}

func (*CommandRequest_Block) isCommandRequest_Request() {}

func (*CommandRequest_ConfigSync) isCommandRequest_Request() {}

func (*CommandRequest_DetectionPackage) isCommandRequest_Request() {}

// SoftwareListRequest 软件列表采集请求
type SoftwareListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareListRequest) Reset() {
	*x = SoftwareListRequest{}
	mi := &file_proto_agent_comm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareListRequest) ProtoMessage() {}

func (x *SoftwareListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareListRequest.ProtoReflect.Descriptor instead.
func (*SoftwareListRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{8}
}

// SoftwareInfo 软件信息
type SoftwareInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	PackageManager string                 `protobuf:"bytes,3,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"` // "rpm" or "dpkg"
	Architecture   string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SoftwareInfo) Reset() {
	*x = SoftwareInfo{}
	mi := &file_proto_agent_comm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareInfo) ProtoMessage() {}

func (x *SoftwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareInfo.ProtoReflect.Descriptor instead.
func (*SoftwareInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{9}
}

func (x *SoftwareInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SoftwareInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SoftwareInfo) GetPackageManager() string {
	if x != nil {
		return x.PackageManager
	}
	return ""
}

func (x *SoftwareInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

// SoftwareListResponse 软件列表采集响应
type SoftwareListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoftwareList  []*SoftwareInfo        `protobuf:"bytes,1,rep,name=software_list,json=softwareList,proto3" json:"software_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareListResponse) Reset() {
	*x = SoftwareListResponse{}
	mi := &file_proto_agent_comm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareListResponse) ProtoMessage() {}

func (x *SoftwareListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareListResponse.ProtoReflect.Descriptor instead.
func (*SoftwareListResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{10}
}

func (x *SoftwareListResponse) GetSoftwareList() []*SoftwareInfo {
	if x != nil {
		return x.SoftwareList
	}
	return nil
}

// RuntimeEvent 运行时事件
type RuntimeEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	HostId           string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname         string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType        string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // process_exec, file_access, network_connect, privilege_change
	ProcessName      string                 `protobuf:"bytes,6,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Pid              int32                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid             int32                  `protobuf:"varint,8,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Uid              int32                  `protobuf:"varint,9,opt,name=uid,proto3" json:"uid,omitempty"`
	CommandLine      string                 `protobuf:"bytes,10,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	FilePath         string                 `protobuf:"bytes,11,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	RemoteAddr       string                 `protobuf:"bytes,12,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	MatchedRuleId    string                 `protobuf:"bytes,13,opt,name=matched_rule_id,json=matchedRuleId,proto3" json:"matched_rule_id,omitempty"`
	MitreId          string                 `protobuf:"bytes,14,opt,name=mitre_id,json=mitreId,proto3" json:"mitre_id,omitempty"`
	Severity         string                 `protobuf:"bytes,15,opt,name=severity,proto3" json:"severity,omitempty"`
	ProcessTree      string                 `protobuf:"bytes,16,opt,name=process_tree,json=processTree,proto3" json:"process_tree,omitempty"`                  // JSON格式的进程树，Agent检测到威胁时自动采集
	MatchedRuleTitle string                 `protobuf:"bytes,17,opt,name=matched_rule_title,json=matchedRuleTitle,proto3" json:"matched_rule_title,omitempty"` // 匹配的规则标题
	EventDataJson    string                 `protobuf:"bytes,18,opt,name=event_data_json,json=eventDataJson,proto3" json:"event_data_json,omitempty"`          // 完整规范化事件 JSON，用于入库、LLM 分析和审计
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RuntimeEvent) Reset() {
	*x = RuntimeEvent{}
	mi := &file_proto_agent_comm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEvent) ProtoMessage() {}

func (x *RuntimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEvent.ProtoReflect.Descriptor instead.
func (*RuntimeEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{11}
}

func (x *RuntimeEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RuntimeEvent) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RuntimeEvent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RuntimeEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RuntimeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RuntimeEvent) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *RuntimeEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RuntimeEvent) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *RuntimeEvent) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RuntimeEvent) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *RuntimeEvent) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *RuntimeEvent) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *RuntimeEvent) GetMatchedRuleId() string {
	if x != nil {
		return x.MatchedRuleId
	}
	return ""
}

func (x *RuntimeEvent) GetMitreId() string {
	if x != nil {
		return x.MitreId
	}
	return ""
}

func (x *RuntimeEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *RuntimeEvent) GetProcessTree() string {
	if x != nil {
		return x.ProcessTree
	}
	return ""
}

func (x *RuntimeEvent) GetMatchedRuleTitle() string {
	if x != nil {
		return x.MatchedRuleTitle
	}
	return ""
}

func (x *RuntimeEvent) GetEventDataJson() string {
	if x != nil {
		return x.EventDataJson
	}
	return ""
}

// ReportEventRequest 事件上报请求
type ReportEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Events        []*RuntimeEvent        `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEventRequest) Reset() {
	*x = ReportEventRequest{}
	mi := &file_proto_agent_comm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventRequest) ProtoMessage() {}

func (x *ReportEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventRequest.ProtoReflect.Descriptor instead.
func (*ReportEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{12}
}

func (x *ReportEventRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ReportEventRequest) GetEvents() []*RuntimeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// ReportEventResponse 事件上报响应
type ReportEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReceivedCount int32                  `protobuf:"varint,2,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEventResponse) Reset() {
	*x = ReportEventResponse{}
	mi := &file_proto_agent_comm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventResponse) ProtoMessage() {}

func (x *ReportEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventResponse.ProtoReflect.Descriptor instead.
func (*ReportEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{13}
}

func (x *ReportEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportEventResponse) GetReceivedCount() int32 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

// ToolRequest 工具调用请求
type ToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Tool          string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`                               // get_process_tree, get_network_connections, etc.
	ParamsJson    string                 `protobuf:"bytes,4,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"` // JSON格式参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_proto_agent_comm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{14}
}

func (x *ToolRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ToolRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

// ToolResponse 工具调用响应
type ToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ResultJson    string                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // JSON格式结果
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_proto_agent_comm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{15}
}

func (x *ToolResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ToolResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RuleUpdate 规则更新
type RuleUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`   // add, update, delete
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // YAML格式Sigma规则
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleUpdate) Reset() {
	*x = RuleUpdate{}
	mi := &file_proto_agent_comm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleUpdate) ProtoMessage() {}

func (x *RuleUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleUpdate.ProtoReflect.Descriptor instead.
func (*RuleUpdate) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{16}
}

func (x *RuleUpdate) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleUpdate) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RuleUpdate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// RuleUpdateRequest 规则更新请求
type RuleUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // full_sync, incremental
	Rules         []*RuleUpdate          `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleUpdateRequest) Reset() {
	*x = RuleUpdateRequest{}
	mi := &file_proto_agent_comm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleUpdateRequest) ProtoMessage() {}

func (x *RuleUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleUpdateRequest.ProtoReflect.Descriptor instead.
func (*RuleUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{17}
}

func (x *RuleUpdateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RuleUpdateRequest) GetRules() []*RuleUpdate {
	if x != nil {
		return x.Rules
	}
	return nil
}

// RuleUpdateResponse 规则更新响应
type RuleUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LoadedCount   int32                  `protobuf:"varint,2,opt,name=loaded_count,json=loadedCount,proto3" json:"loaded_count,omitempty"`
	Rules         []*RuleUpdate          `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleUpdateResponse) Reset() {
	*x = RuleUpdateResponse{}
	mi := &file_proto_agent_comm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleUpdateResponse) ProtoMessage() {}

func (x *RuleUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleUpdateResponse.ProtoReflect.Descriptor instead.
func (*RuleUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{18}
}

func (x *RuleUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RuleUpdateResponse) GetLoadedCount() int32 {
	if x != nil {
		return x.LoadedCount
	}
	return 0
}

func (x *RuleUpdateResponse) GetRules() []*RuleUpdate {
	if x != nil {
		return x.Rules
	}
	return nil
}

// BlockCommand 阻断指令
type BlockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // kill_process
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"` // PID
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCommand) Reset() {
	*x = BlockCommand{}
	mi := &file_proto_agent_comm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCommand) ProtoMessage() {}

func (x *BlockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCommand.ProtoReflect.Descriptor instead.
func (*BlockCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{19}
}

func (x *BlockCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *BlockCommand) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *BlockCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *BlockCommand) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *BlockCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// BlockResponse 阻断响应
type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_proto_agent_comm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{20}
}

func (x *BlockResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *BlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ConfigSync 配置同步
type ConfigSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigType    string                 `protobuf:"bytes,1,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"` // "sigma_rules", "audit_rules", "audit_settings", "dynamic_ebpf_hook_allowlist"
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`                           // "full_sync", "incremental"
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                         // JSON格式配置内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSync) Reset() {
	*x = ConfigSync{}
	mi := &file_proto_agent_comm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSync) ProtoMessage() {}

func (x *ConfigSync) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSync.ProtoReflect.Descriptor instead.
func (*ConfigSync) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{21}
}

func (x *ConfigSync) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *ConfigSync) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ConfigSync) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// V5.8 DetectionPackageCommand 检测包命令
type DetectionPackageCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // install, uninstall, disable
	PackageId     string                 `protobuf:"bytes,3,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	PackageUrl    string                 `protobuf:"bytes,5,opt,name=package_url,json=packageUrl,proto3" json:"package_url,omitempty"`       // MinIO download URL
	SignatureUrl  string                 `protobuf:"bytes,6,opt,name=signature_url,json=signatureUrl,proto3" json:"signature_url,omitempty"` // MinIO download URL for .sig
	PackageSize   int64                  `protobuf:"varint,7,opt,name=package_size,json=packageSize,proto3" json:"package_size,omitempty"`
	Rollback      bool                   `protobuf:"varint,8,opt,name=rollback,proto3" json:"rollback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionPackageCommand) Reset() {
	*x = DetectionPackageCommand{}
	mi := &file_proto_agent_comm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionPackageCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionPackageCommand) ProtoMessage() {}

func (x *DetectionPackageCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionPackageCommand.ProtoReflect.Descriptor instead.
func (*DetectionPackageCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{22}
}

func (x *DetectionPackageCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *DetectionPackageCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DetectionPackageCommand) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *DetectionPackageCommand) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DetectionPackageCommand) GetPackageUrl() string {
	if x != nil {
		return x.PackageUrl
	}
	return ""
}

func (x *DetectionPackageCommand) GetSignatureUrl() string {
	if x != nil {
		return x.SignatureUrl
	}
	return ""
}

func (x *DetectionPackageCommand) GetPackageSize() int64 {
	if x != nil {
		return x.PackageSize
	}
	return 0
}

func (x *DetectionPackageCommand) GetRollback() bool {
	if x != nil {
		return x.Rollback
	}
	return false
}

// DetectionPackageStatus 检测包状态上报
type DetectionPackageStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PackageId      string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                       // active, degraded, load_failed, etc.
	ActiveArtifact string                 `protobuf:"bytes,4,opt,name=active_artifact,json=activeArtifact,proto3" json:"active_artifact,omitempty"` // ringbuf, perf
	LoadedHooks    []string               `protobuf:"bytes,5,rep,name=loaded_hooks,json=loadedHooks,proto3" json:"loaded_hooks,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ReportedAt     int64                  `protobuf:"varint,7,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetectionPackageStatus) Reset() {
	*x = DetectionPackageStatus{}
	mi := &file_proto_agent_comm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionPackageStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionPackageStatus) ProtoMessage() {}

func (x *DetectionPackageStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionPackageStatus.ProtoReflect.Descriptor instead.
func (*DetectionPackageStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{23}
}

func (x *DetectionPackageStatus) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *DetectionPackageStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DetectionPackageStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DetectionPackageStatus) GetActiveArtifact() string {
	if x != nil {
		return x.ActiveArtifact
	}
	return ""
}

func (x *DetectionPackageStatus) GetLoadedHooks() []string {
	if x != nil {
		return x.LoadedHooks
	}
	return nil
}

func (x *DetectionPackageStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DetectionPackageStatus) GetReportedAt() int64 {
	if x != nil {
		return x.ReportedAt
	}
	return 0
}

// ConfigSyncRequest 配置同步请求
type ConfigSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ConfigSync          `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSyncRequest) Reset() {
	*x = ConfigSyncRequest{}
	mi := &file_proto_agent_comm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSyncRequest) ProtoMessage() {}

func (x *ConfigSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSyncRequest.ProtoReflect.Descriptor instead.
func (*ConfigSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{24}
}

func (x *ConfigSyncRequest) GetConfigs() []*ConfigSync {
	if x != nil {
		return x.Configs
	}
	return nil
}

// ConfigSyncResponse 配置同步响应
type ConfigSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Applied       map[string]bool        `protobuf:"bytes,3,rep,name=applied,proto3" json:"applied,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // config_type -> success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSyncResponse) Reset() {
	*x = ConfigSyncResponse{}
	mi := &file_proto_agent_comm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSyncResponse) ProtoMessage() {}

func (x *ConfigSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_comm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSyncResponse.ProtoReflect.Descriptor instead.
func (*ConfigSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_comm_proto_rawDescGZIP(), []int{25}
}

func (x *ConfigSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigSyncResponse) GetApplied() map[string]bool {
	if x != nil {
		return x.Applied
	}
	return nil
}

var File_proto_agent_comm_proto protoreflect.FileDescriptor

const file_proto_agent_comm_proto_rawDesc = "" +
	"\n" +
	"\x16proto/agent_comm.proto\x12\ragent_comm.v1\"\xb7\x01\n" +
	"\tAssetInfo\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_type\x18\x03 \x01(\tR\x06osType\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\"\xa7\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x127\n" +
	"\n" +
	"asset_info\x18\x02 \x01(\v2\x18.agent_comm.v1.AssetInfoR\tassetInfo\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\x12#\n" +
	"\rcallback_port\x18\x04 \x01(\x05R\fcallbackPort\"_\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"I\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xab\x01\n" +
	"\x0eCommandExecute\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\x12%\n" +
	"\x0escript_content\x18\x04 \x01(\tR\rscriptContent\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"\xa9\x01\n" +
	"\rCommandResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x19\n" +
	"\bis_final\x18\x06 \x01(\bR\aisFinal\"\x9d\x03\n" +
	"\x0eCommandRequest\x129\n" +
	"\aexecute\x18\x01 \x01(\v2\x1d.agent_comm.v1.CommandExecuteH\x00R\aexecute\x126\n" +
	"\x06result\x18\x02 \x01(\v2\x1c.agent_comm.v1.CommandResultH\x00R\x06result\x12C\n" +
	"\vrule_update\x18\x03 \x01(\v2 .agent_comm.v1.RuleUpdateRequestH\x00R\n" +
	"ruleUpdate\x123\n" +
	"\x05block\x18\x04 \x01(\v2\x1b.agent_comm.v1.BlockCommandH\x00R\x05block\x12<\n" +
	"\vconfig_sync\x18\x05 \x01(\v2\x19.agent_comm.v1.ConfigSyncH\x00R\n" +
	"configSync\x12U\n" +
	"\x11detection_package\x18\x06 \x01(\v2&.agent_comm.v1.DetectionPackageCommandH\x00R\x10detectionPackageB\t\n" +
	"\arequest\"\x15\n" +
	"\x13SoftwareListRequest\"\x89\x01\n" +
	"\fSoftwareInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12'\n" +
	"\x0fpackage_manager\x18\x03 \x01(\tR\x0epackageManager\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\"X\n" +
	"\x14SoftwareListResponse\x12@\n" +
	"\rsoftware_list\x18\x01 \x03(\v2\x1b.agent_comm.v1.SoftwareInfoR\fsoftwareList\"\xaf\x04\n" +
	"\fRuntimeEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12!\n" +
	"\fprocess_name\x18\x06 \x01(\tR\vprocessName\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\b \x01(\x05R\x04ppid\x12\x10\n" +
	"\x03uid\x18\t \x01(\x05R\x03uid\x12!\n" +
	"\fcommand_line\x18\n" +
	" \x01(\tR\vcommandLine\x12\x1b\n" +
	"\tfile_path\x18\v \x01(\tR\bfilePath\x12\x1f\n" +
	"\vremote_addr\x18\f \x01(\tR\n" +
	"remoteAddr\x12&\n" +
	"\x0fmatched_rule_id\x18\r \x01(\tR\rmatchedRuleId\x12\x19\n" +
	"\bmitre_id\x18\x0e \x01(\tR\amitreId\x12\x1a\n" +
	"\bseverity\x18\x0f \x01(\tR\bseverity\x12!\n" +
	"\fprocess_tree\x18\x10 \x01(\tR\vprocessTree\x12,\n" +
	"\x12matched_rule_title\x18\x11 \x01(\tR\x10matchedRuleTitle\x12&\n" +
	"\x0fevent_data_json\x18\x12 \x01(\tR\reventDataJson\"b\n" +
	"\x12ReportEventRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x123\n" +
	"\x06events\x18\x02 \x03(\v2\x1b.agent_comm.v1.RuntimeEventR\x06events\"V\n" +
	"\x13ReportEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ereceived_count\x18\x02 \x01(\x05R\rreceivedCount\"t\n" +
	"\vToolRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12\x1f\n" +
	"\vparams_json\x18\x04 \x01(\tR\n" +
	"paramsJson\"x\n" +
	"\fToolResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"W\n" +
	"\n" +
	"RuleUpdate\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\\\n" +
	"\x11RuleUpdateRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12/\n" +
	"\x05rules\x18\x02 \x03(\v2\x19.agent_comm.v1.RuleUpdateR\x05rules\"\x82\x01\n" +
	"\x12RuleUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\floaded_count\x18\x02 \x01(\x05R\vloadedCount\x12/\n" +
	"\x05rules\x18\x03 \x03(\v2\x19.agent_comm.v1.RuleUpdateR\x05rules\"\x8e\x01\n" +
	"\fBlockCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"^\n" +
	"\rBlockResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"_\n" +
	"\n" +
	"ConfigSync\x12\x1f\n" +
	"\vconfig_type\x18\x01 \x01(\tR\n" +
	"configType\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"\x8e\x02\n" +
	"\x17DetectionPackageCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"package_id\x18\x03 \x01(\tR\tpackageId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1f\n" +
	"\vpackage_url\x18\x05 \x01(\tR\n" +
	"packageUrl\x12#\n" +
	"\rsignature_url\x18\x06 \x01(\tR\fsignatureUrl\x12!\n" +
	"\fpackage_size\x18\a \x01(\x03R\vpackageSize\x12\x1a\n" +
	"\brollback\x18\b \x01(\bR\brollback\"\xfb\x01\n" +
	"\x16DetectionPackageStatus\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0factive_artifact\x18\x04 \x01(\tR\x0eactiveArtifact\x12!\n" +
	"\floaded_hooks\x18\x05 \x03(\tR\vloadedHooks\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vreported_at\x18\a \x01(\x03R\n" +
	"reportedAt\"H\n" +
	"\x11ConfigSyncRequest\x123\n" +
	"\aconfigs\x18\x01 \x03(\v2\x19.agent_comm.v1.ConfigSyncR\aconfigs\"\xce\x01\n" +
	"\x12ConfigSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12H\n" +
	"\aapplied\x18\x03 \x03(\v2..agent_comm.v1.ConfigSyncResponse.AppliedEntryR\aapplied\x1a:\n" +
	"\fAppliedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x012\xf6\x05\n" +
	"\fAgentService\x12K\n" +
	"\bRegister\x12\x1e.agent_comm.v1.RegisterRequest\x1a\x1f.agent_comm.v1.RegisterResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.agent_comm.v1.HeartbeatRequest\x1a .agent_comm.v1.HeartbeatResponse\x12R\n" +
	"\x0eExecuteCommand\x12\x1d.agent_comm.v1.CommandRequest\x1a\x1d.agent_comm.v1.CommandRequest(\x010\x01\x12^\n" +
	"\x13CollectSoftwareList\x12\".agent_comm.v1.SoftwareListRequest\x1a#.agent_comm.v1.SoftwareListResponse\x12T\n" +
	"\vReportEvent\x12!.agent_comm.v1.ReportEventRequest\x1a\".agent_comm.v1.ReportEventResponse\x12F\n" +
	"\vExecuteTool\x12\x1a.agent_comm.v1.ToolRequest\x1a\x1b.agent_comm.v1.ToolResponse\x12R\n" +
	"\vUpdateRules\x12 .agent_comm.v1.RuleUpdateRequest\x1a!.agent_comm.v1.RuleUpdateResponse\x12P\n" +
	"\x13ExecuteBlockCommand\x12\x1b.agent_comm.v1.BlockCommand\x1a\x1c.agent_comm.v1.BlockResponse\x12Q\n" +
	"\n" +
	"SyncConfig\x12 .agent_comm.v1.ConfigSyncRequest\x1a!.agent_comm.v1.ConfigSyncResponseB\x16Z\x14server/pkg/api/v1;pbb\x06proto3"

var (
	file_proto_agent_comm_proto_rawDescOnce sync.Once
	file_proto_agent_comm_proto_rawDescData []byte
)

func file_proto_agent_comm_proto_rawDescGZIP() []byte {
	file_proto_agent_comm_proto_rawDescOnce.Do(func() {
		file_proto_agent_comm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_comm_proto_rawDesc), len(file_proto_agent_comm_proto_rawDesc)))
	})
	return file_proto_agent_comm_proto_rawDescData
}

var file_proto_agent_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_agent_comm_proto_goTypes = []any{
	(*AssetInfo)(nil),               // 0: agent_comm.v1.AssetInfo
	(*RegisterRequest)(nil),         // 1: agent_comm.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 2: agent_comm.v1.RegisterResponse
	(*HeartbeatRequest)(nil),        // 3: agent_comm.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 4: agent_comm.v1.HeartbeatResponse
	(*CommandExecute)(nil),          // 5: agent_comm.v1.CommandExecute
	(*CommandResult)(nil),           // 6: agent_comm.v1.CommandResult
	(*CommandRequest)(nil),          // 7: agent_comm.v1.CommandRequest
	(*SoftwareListRequest)(nil),     // 8: agent_comm.v1.SoftwareListRequest
	(*SoftwareInfo)(nil),            // 9: agent_comm.v1.SoftwareInfo
	(*SoftwareListResponse)(nil),    // 10: agent_comm.v1.SoftwareListResponse
	(*RuntimeEvent)(nil),            // 11: agent_comm.v1.RuntimeEvent
	(*ReportEventRequest)(nil),      // 12: agent_comm.v1.ReportEventRequest
	(*ReportEventResponse)(nil),     // 13: agent_comm.v1.ReportEventResponse
	(*ToolRequest)(nil),             // 14: agent_comm.v1.ToolRequest
	(*ToolResponse)(nil),            // 15: agent_comm.v1.ToolResponse
	(*RuleUpdate)(nil),              // 16: agent_comm.v1.RuleUpdate
	(*RuleUpdateRequest)(nil),       // 17: agent_comm.v1.RuleUpdateRequest
	(*RuleUpdateResponse)(nil),      // 18: agent_comm.v1.RuleUpdateResponse
	(*BlockCommand)(nil),            // 19: agent_comm.v1.BlockCommand
	(*BlockResponse)(nil),           // 20: agent_comm.v1.BlockResponse
	(*ConfigSync)(nil),              // 21: agent_comm.v1.ConfigSync
	(*DetectionPackageCommand)(nil), // 22: agent_comm.v1.DetectionPackageCommand
	(*DetectionPackageStatus)(nil),  // 23: agent_comm.v1.DetectionPackageStatus
	(*ConfigSyncRequest)(nil),       // 24: agent_comm.v1.ConfigSyncRequest
	(*ConfigSyncResponse)(nil),      // 25: agent_comm.v1.ConfigSyncResponse
	nil,                             // 26: agent_comm.v1.ConfigSyncResponse.AppliedEntry
}
var file_proto_agent_comm_proto_depIdxs = []int32{
	0,  // 0: agent_comm.v1.RegisterRequest.asset_info:type_name -> agent_comm.v1.AssetInfo
	5,  // 1: agent_comm.v1.CommandRequest.execute:type_name -> agent_comm.v1.CommandExecute
	6,  // 2: agent_comm.v1.CommandRequest.result:type_name -> agent_comm.v1.CommandResult
	17, // 3: agent_comm.v1.CommandRequest.rule_update:type_name -> agent_comm.v1.RuleUpdateRequest
	19, // 4: agent_comm.v1.CommandRequest.block:type_name -> agent_comm.v1.BlockCommand
	21, // 5: agent_comm.v1.CommandRequest.config_sync:type_name -> agent_comm.v1.ConfigSync
	22, // 6: agent_comm.v1.CommandRequest.detection_package:type_name -> agent_comm.v1.DetectionPackageCommand
	9,  // 7: agent_comm.v1.SoftwareListResponse.software_list:type_name -> agent_comm.v1.SoftwareInfo
	11, // 8: agent_comm.v1.ReportEventRequest.events:type_name -> agent_comm.v1.RuntimeEvent
	16, // 9: agent_comm.v1.RuleUpdateRequest.rules:type_name -> agent_comm.v1.RuleUpdate
	16, // 10: agent_comm.v1.RuleUpdateResponse.rules:type_name -> agent_comm.v1.RuleUpdate
	21, // 11: agent_comm.v1.ConfigSyncRequest.configs:type_name -> agent_comm.v1.ConfigSync
	26, // 12: agent_comm.v1.ConfigSyncResponse.applied:type_name -> agent_comm.v1.ConfigSyncResponse.AppliedEntry
	1,  // 13: agent_comm.v1.AgentService.Register:input_type -> agent_comm.v1.RegisterRequest
	3,  // 14: agent_comm.v1.AgentService.Heartbeat:input_type -> agent_comm.v1.HeartbeatRequest
	7,  // 15: agent_comm.v1.AgentService.ExecuteCommand:input_type -> agent_comm.v1.CommandRequest
	8,  // 16: agent_comm.v1.AgentService.CollectSoftwareList:input_type -> agent_comm.v1.SoftwareListRequest
	12, // 17: agent_comm.v1.AgentService.ReportEvent:input_type -> agent_comm.v1.ReportEventRequest
	14, // 18: agent_comm.v1.AgentService.ExecuteTool:input_type -> agent_comm.v1.ToolRequest
	17, // 19: agent_comm.v1.AgentService.UpdateRules:input_type -> agent_comm.v1.RuleUpdateRequest
	19, // 20: agent_comm.v1.AgentService.ExecuteBlockCommand:input_type -> agent_comm.v1.BlockCommand
	24, // 21: agent_comm.v1.AgentService.SyncConfig:input_type -> agent_comm.v1.ConfigSyncRequest
	2,  // 22: agent_comm.v1.AgentService.Register:output_type -> agent_comm.v1.RegisterResponse
	4,  // 23: agent_comm.v1.AgentService.Heartbeat:output_type -> agent_comm.v1.HeartbeatResponse
	7,  // 24: agent_comm.v1.AgentService.ExecuteCommand:output_type -> agent_comm.v1.CommandRequest
	10, // 25: agent_comm.v1.AgentService.CollectSoftwareList:output_type -> agent_comm.v1.SoftwareListResponse
	13, // 26: agent_comm.v1.AgentService.ReportEvent:output_type -> agent_comm.v1.ReportEventResponse
	15, // 27: agent_comm.v1.AgentService.ExecuteTool:output_type -> agent_comm.v1.ToolResponse
	18, // 28: agent_comm.v1.AgentService.UpdateRules:output_type -> agent_comm.v1.RuleUpdateResponse
	20, // 29: agent_comm.v1.AgentService.ExecuteBlockCommand:output_type -> agent_comm.v1.BlockResponse
	25, // 30: agent_comm.v1.AgentService.SyncConfig:output_type -> agent_comm.v1.ConfigSyncResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_agent_comm_proto_init() }
func file_proto_agent_comm_proto_init() {
	if File_proto_agent_comm_proto != nil {
		return
	}
	file_proto_agent_comm_proto_msgTypes[7].OneofWrappers = []any{
		(*CommandRequest_Execute)(nil),
		(*CommandRequest_Result)(nil),
		(*CommandRequest_RuleUpdate)(nil),
		(*CommandRequest_Block)(nil),
		(*CommandRequest_ConfigSync)(nil),
		(*CommandRequest_DetectionPackage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_comm_proto_rawDesc), len(file_proto_agent_comm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_comm_proto_goTypes,
		DependencyIndexes: file_proto_agent_comm_proto_depIdxs,
		MessageInfos:      file_proto_agent_comm_proto_msgTypes,
	}.Build()
	File_proto_agent_comm_proto = out.File
	file_proto_agent_comm_proto_goTypes = nil
	file_proto_agent_comm_proto_depIdxs = nil
}
